/*
 * Decompiled with CFR 0.150.
 */
import com.a.a.d.aad;
import java.util.Set;

public class blg {
    private static final Set dl;
    public static final bfa a;
    public static final bfa b;
    public static final bs c;
    public static final bfa d;
    public static final bfa e;
    public static final bfa f;
    public static final bfa g;
    public static final bfa h;
    public static final cyi i;
    public static final arf j;
    public static final cyi k;
    public static final arf l;
    public static final bhg m;
    public static final bfa n;
    public static final bfa o;
    public static final bfa p;
    public static final bfa q;
    public static final bfa r;
    public static final bfa s;
    public static final aai t;
    public static final aai u;
    public static final bfa v;
    public static final bfa w;
    public static final bfa x;
    public static final bfa y;
    public static final bfa z;
    public static final bfa A;
    public static final bfa B;
    public static final bfa C;
    public static final bfa D;
    public static final bfa E;
    public static final ath F;
    public static final bfa G;
    public static final add H;
    public static final asn I;
    public static final ath J;
    public static final ln K;
    public static final bfa L;
    public static final pk M;
    public static final amh N;
    public static final amh O;
    public static final lp P;
    public static final lp Q;
    public static final bfa R;
    public static final bfa S;
    public static final bnr T;
    public static final bnr U;
    public static final bfa V;
    public static final bfa W;
    public static final bfa X;
    public static final bfa Y;
    public static final bfa Z;
    public static final bfa aa;
    public static final art ab;
    public static final bfa ac;
    public static final bfa ad;
    public static final aqi ae;
    public static final czs af;
    public static final bfa ag;
    public static final bfa ah;
    public static final bfa ai;
    public static final bfa aj;
    public static final bfa ak;
    public static final bfa al;
    public static final bfa am;
    public static final bfa an;
    public static final xt ao;
    public static final xt ap;
    public static final xt aq;
    public static final xt ar;
    public static final xt as;
    public static final xt at;
    public static final bfa au;
    public static final bfa av;
    public static final bfa aw;
    public static final bfa ax;
    public static final bfa ay;
    public static final bfa az;
    public static final xt aA;
    public static final bfa aB;
    public static final bfa aC;
    public static final bfa aD;
    public static final bfa aE;
    public static final bfa aF;
    public static final bfa aG;
    public static final bfa aH;
    public static final bfa aI;
    public static final bfa aJ;
    public static final qt aK;
    public static final bfa aL;
    public static final bxe aM;
    public static final bfa aN;
    public static final bfa aO;
    public static final bfa aP;
    public static final bfa aQ;
    public static final bfa aR;
    public static final bfa aS;
    public static final bfa aT;
    public static final bfa aU;
    public static final bfa aV;
    public static final bfa aW;
    public static final bfa aX;
    public static final axz aY;
    public static final bfa aZ;
    public static final bfa ba;
    public static final xc bb;
    public static final xc bc;
    public static final bfa bd;
    public static final bfa be;
    public static final bfa bf;
    public static final bfa bg;
    public static final bfa bh;
    public static final bfa bi;
    public static final bfa bj;
    public static final bfa bk;
    public static final bfa bl;
    public static final bfa bm;
    public static final bfa bn;
    public static final bfa bo;
    public static final bfa bp;
    public static final bfa bq;
    public static final bfa br;
    public static final bfa bs;
    public static final bfa bt;
    public static final bfa bu;
    public static final bfa bv;
    public static final sg bw;
    public static final bfa bx;
    public static final bfa by;
    public static final bfa bz;
    public static final bfa bA;
    public static final bfa bB;
    public static final bfa bC;
    public static final bfa bD;
    public static final auf bE;
    public static final bfa bF;
    public static final bfa bG;
    public static final bfa bH;
    public static final bfa bI;
    public static final bfa bJ;
    public static final bfa bK;
    public static final bnr bL;
    public static final bnr bM;
    public static final bfa bN;
    public static final bfa bO;
    public static final bfa bP;
    public static final bfa bQ;
    public static final cr bR;
    public static final bfa bS;
    public static final bfa bT;
    public static final bfa bU;
    public static final bfa bV;
    public static final bfa bW;
    public static final bfa bX;
    public static final aga bY;
    public static final bfa bZ;
    public static final bfa ca;
    public static final bfa cb;
    public static final bfa cc;
    public static final bfa cd;
    public static final cvc ce;
    public static final bfa cf;
    public static final bfa cg;
    public static final bfa ch;
    public static final bfa ci;
    public static final bra cj;
    public static final bra ck;
    public static final lu cl;
    public static final lu cm;
    public static final bfa cn;
    public static final bfa co;
    public static final ao cp;
    public static final bfa cq;
    public static final bfa cr;
    public static final bfa cs;
    public static final bfa ct;
    public static final bfa cu;
    public static final bfa cv;
    public static final bfa cw;
    public static final bfa cx;
    public static final bfa cy;
    public static final bfa cz;
    public static final bfa cA;
    public static final bfa cB;
    public static final bfa cC;
    public static final bfa cD;
    public static final bfa cE;
    public static final aqr cF;
    public static final ajr cG;
    public static final cqe cH;
    public static final bfa cI;
    public static final bfa cJ;
    public static final bfa cK;
    public static final bfa cL;
    public static final bfa cM;
    public static final bfa cN;
    public static final bnr cO;
    public static final bnr cP;
    public static final bfa cQ;
    public static final bfa cR;
    public static final bfa cS;
    public static final bfa cT;
    public static final bfa cU;
    public static final bfa cV;
    public static final bnr cW;
    public static final bnr cX;
    public static final bfa cY;
    public static final bfa cZ;
    public static final bfa da;
    public static final bfa db;
    public static final bfa dc;
    public static final bfa dd;
    public static final bfa de;
    public static final bfa df;
    public static final bfa dg;
    public static final bfa dh;
    public static final bfa di;
    public static final bfa dj;
    public static final bfa dk;

    private static bfa a(String string) {
        bfa bfa2 = (bfa)bfa.v.c(new bpx(string));
        if (!dl.add(bfa2)) {
            throw new IllegalStateException("Invalid Block requested: " + string);
        }
        return bfa2;
    }

    static {
        if (!bht.a()) {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }
        dl = aad.a();
        a = blg.a("air");
        b = blg.a("stone");
        c = (bs)blg.a("grass");
        d = blg.a("dirt");
        e = blg.a("cobblestone");
        f = blg.a("planks");
        g = blg.a("sapling");
        h = blg.a("bedrock");
        i = (cyi)blg.a("flowing_water");
        j = (arf)blg.a("water");
        k = (cyi)blg.a("flowing_lava");
        l = (arf)blg.a("lava");
        m = (bhg)blg.a("sand");
        n = blg.a("gravel");
        o = blg.a("gold_ore");
        p = blg.a("iron_ore");
        q = blg.a("coal_ore");
        r = blg.a("log");
        s = blg.a("log2");
        t = (aai)blg.a("leaves");
        u = (aai)blg.a("leaves2");
        v = blg.a("sponge");
        w = blg.a("glass");
        x = blg.a("lapis_ore");
        y = blg.a("lapis_block");
        z = blg.a("dispenser");
        A = blg.a("sandstone");
        B = blg.a("noteblock");
        C = blg.a("bed");
        D = blg.a("golden_rail");
        E = blg.a("detector_rail");
        F = (ath)blg.a("sticky_piston");
        G = blg.a("web");
        H = (add)blg.a("tallgrass");
        I = (asn)blg.a("deadbush");
        J = (ath)blg.a("piston");
        K = (ln)blg.a("piston_head");
        L = blg.a("wool");
        M = (pk)blg.a("piston_extension");
        N = (amh)blg.a("yellow_flower");
        O = (amh)blg.a("red_flower");
        P = (lp)blg.a("brown_mushroom");
        Q = (lp)blg.a("red_mushroom");
        R = blg.a("gold_block");
        S = blg.a("iron_block");
        T = (bnr)blg.a("double_stone_slab");
        U = (bnr)blg.a("stone_slab");
        V = blg.a("brick_block");
        W = blg.a("tnt");
        X = blg.a("bookshelf");
        Y = blg.a("mossy_cobblestone");
        Z = blg.a("obsidian");
        aa = blg.a("torch");
        ab = (art)blg.a("fire");
        ac = blg.a("mob_spawner");
        ad = blg.a("oak_stairs");
        ae = (aqi)blg.a("chest");
        af = (czs)blg.a("redstone_wire");
        ag = blg.a("diamond_ore");
        ah = blg.a("diamond_block");
        ai = blg.a("crafting_table");
        aj = blg.a("wheat");
        ak = blg.a("farmland");
        al = blg.a("furnace");
        am = blg.a("lit_furnace");
        an = blg.a("standing_sign");
        ao = (xt)blg.a("wooden_door");
        ap = (xt)blg.a("spruce_door");
        aq = (xt)blg.a("birch_door");
        ar = (xt)blg.a("jungle_door");
        as = (xt)blg.a("acacia_door");
        at = (xt)blg.a("dark_oak_door");
        au = blg.a("ladder");
        av = blg.a("rail");
        aw = blg.a("stone_stairs");
        ax = blg.a("wall_sign");
        ay = blg.a("lever");
        az = blg.a("stone_pressure_plate");
        aA = (xt)blg.a("iron_door");
        aB = blg.a("wooden_pressure_plate");
        aC = blg.a("redstone_ore");
        aD = blg.a("lit_redstone_ore");
        aE = blg.a("unlit_redstone_torch");
        aF = blg.a("redstone_torch");
        aG = blg.a("stone_button");
        aH = blg.a("snow_layer");
        aI = blg.a("ice");
        aJ = blg.a("snow");
        aK = (qt)blg.a("cactus");
        aL = blg.a("clay");
        aM = (bxe)blg.a("reeds");
        aN = blg.a("jukebox");
        aO = blg.a("fence");
        aP = blg.a("spruce_fence");
        aQ = blg.a("birch_fence");
        aR = blg.a("jungle_fence");
        aS = blg.a("dark_oak_fence");
        aT = blg.a("acacia_fence");
        aU = blg.a("pumpkin");
        aV = blg.a("netherrack");
        aW = blg.a("soul_sand");
        aX = blg.a("glowstone");
        aY = (axz)blg.a("portal");
        aZ = blg.a("lit_pumpkin");
        ba = blg.a("cake");
        bb = (xc)blg.a("unpowered_repeater");
        bc = (xc)blg.a("powered_repeater");
        bd = blg.a("trapdoor");
        be = blg.a("monster_egg");
        bf = blg.a("stonebrick");
        bg = blg.a("brown_mushroom_block");
        bh = blg.a("red_mushroom_block");
        bi = blg.a("iron_bars");
        bj = blg.a("glass_pane");
        bk = blg.a("melon_block");
        bl = blg.a("pumpkin_stem");
        bm = blg.a("melon_stem");
        bn = blg.a("vine");
        bo = blg.a("fence_gate");
        bp = blg.a("spruce_fence_gate");
        bq = blg.a("birch_fence_gate");
        br = blg.a("jungle_fence_gate");
        bs = blg.a("dark_oak_fence_gate");
        bt = blg.a("acacia_fence_gate");
        bu = blg.a("brick_stairs");
        bv = blg.a("stone_brick_stairs");
        bw = (sg)blg.a("mycelium");
        bx = blg.a("waterlily");
        by = blg.a("nether_brick");
        bz = blg.a("nether_brick_fence");
        bA = blg.a("nether_brick_stairs");
        bB = blg.a("nether_wart");
        bC = blg.a("enchanting_table");
        bD = blg.a("brewing_stand");
        bE = (auf)blg.a("cauldron");
        bF = blg.a("end_portal");
        bG = blg.a("end_portal_frame");
        bH = blg.a("end_stone");
        bI = blg.a("dragon_egg");
        bJ = blg.a("redstone_lamp");
        bK = blg.a("lit_redstone_lamp");
        bL = (bnr)blg.a("double_wooden_slab");
        bM = (bnr)blg.a("wooden_slab");
        bN = blg.a("cocoa");
        bO = blg.a("sandstone_stairs");
        bP = blg.a("emerald_ore");
        bQ = blg.a("ender_chest");
        bR = (cr)blg.a("tripwire_hook");
        bS = blg.a("tripwire");
        bT = blg.a("emerald_block");
        bU = blg.a("spruce_stairs");
        bV = blg.a("birch_stairs");
        bW = blg.a("jungle_stairs");
        bX = blg.a("command_block");
        bY = (aga)blg.a("beacon");
        bZ = blg.a("cobblestone_wall");
        ca = blg.a("flower_pot");
        cb = blg.a("carrots");
        cc = blg.a("potatoes");
        cd = blg.a("wooden_button");
        ce = (cvc)blg.a("skull");
        cf = blg.a("anvil");
        cg = blg.a("trapped_chest");
        ch = blg.a("light_weighted_pressure_plate");
        ci = blg.a("heavy_weighted_pressure_plate");
        cj = (bra)blg.a("unpowered_comparator");
        ck = (bra)blg.a("powered_comparator");
        cl = (lu)blg.a("daylight_detector");
        cm = (lu)blg.a("daylight_detector_inverted");
        cn = blg.a("redstone_block");
        co = blg.a("quartz_ore");
        cp = (ao)blg.a("hopper");
        cq = blg.a("quartz_block");
        cr = blg.a("quartz_stairs");
        cs = blg.a("activator_rail");
        ct = blg.a("dropper");
        cu = blg.a("stained_hardened_clay");
        cv = blg.a("barrier");
        cw = blg.a("iron_trapdoor");
        cx = blg.a("hay_block");
        cy = blg.a("carpet");
        cz = blg.a("hardened_clay");
        cA = blg.a("coal_block");
        cB = blg.a("packed_ice");
        cC = blg.a("acacia_stairs");
        cD = blg.a("dark_oak_stairs");
        cE = blg.a("slime");
        cF = (aqr)blg.a("double_plant");
        cG = (ajr)blg.a("stained_glass");
        cH = (cqe)blg.a("stained_glass_pane");
        cI = blg.a("prismarine");
        cJ = blg.a("sea_lantern");
        cK = blg.a("standing_banner");
        cL = blg.a("wall_banner");
        cM = blg.a("red_sandstone");
        cN = blg.a("red_sandstone_stairs");
        cO = (bnr)blg.a("double_stone_slab2");
        cP = (bnr)blg.a("stone_slab2");
        cQ = blg.a("end_rod");
        cR = blg.a("chorus_plant");
        cS = blg.a("chorus_flower");
        cT = blg.a("purpur_block");
        cU = blg.a("purpur_pillar");
        cV = blg.a("purpur_stairs");
        cW = (bnr)blg.a("purpur_double_slab");
        cX = (bnr)blg.a("purpur_slab");
        cY = blg.a("end_bricks");
        cZ = blg.a("beetroots");
        da = blg.a("grass_path");
        db = blg.a("end_gateway");
        dc = blg.a("repeating_command_block");
        dd = blg.a("chain_command_block");
        de = blg.a("frosted_ice");
        df = blg.a("magma");
        dg = blg.a("nether_wart_block");
        dh = blg.a("red_nether_brick");
        di = blg.a("bone_block");
        dj = blg.a("structure_void");
        dk = blg.a("structure_block");
        dl.clear();
    }
}

