/*
 * Decompiled with CFR 0.150.
 */
/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public class dah {
    public static final bi a;
    public static final bi b;
    public static final bi c;
    public static final bi d;
    public static final bi e;
    public static final bi f;
    public static final bi g;
    public static final bi h;
    public static final bi i;
    public static final bi j;
    public static final bi k;
    public static final bi l;
    public static final bi m;
    public static final bi n;
    public static final bi o;
    public static final bi p;
    public static final bi q;
    public static final bi r;
    public static final bi s;
    public static final bi t;
    public static final bi u;
    public static final bi v;
    public static final bi w;
    public static final bi x;
    public static final bi y;
    public static final bi z;
    public static final bi A;
    public static final bi B;
    public static final bi C;
    public static final bi D;
    public static final bi E;
    public static final bi F;
    public static final bi G;
    public static final bi H;
    public static final bi I;
    public static final bi J;
    public static final bi K;
    public static final bi L;
    public static final bi M;
    public static final bi N;
    public static final bi O;
    public static final bi P;
    public static final bi Q;
    public static final bi R;
    public static final bi S;
    public static final bi T;
    public static final bi U;
    public static final bi V;
    public static final bi W;
    public static final bi X;
    public static final bi Y;
    public static final bi Z;
    public static final bi aa;
    public static final bi ab;
    public static final bi ac;
    public static final bi ad;
    public static final bi ae;
    public static final bi af;
    public static final bi ag;
    public static final bi ah;
    public static final bi ai;
    public static final bi aj;
    public static final bi ak;
    public static final bi al;
    public static final bi am;
    public static final bi an;
    public static final bi ao;
    public static final bi ap;
    public static final bi aq;
    public static final bi ar;
    public static final bi as;
    public static final bi at;
    public static final bi au;
    public static final bi av;
    public static final bi aw;
    public static final bi ax;
    public static final bi ay;
    public static final bi az;
    public static final bi aA;
    public static final bi aB;
    public static final bi aC;
    public static final bi aD;
    public static final bi aE;
    public static final bi aF;
    public static final bi aG;
    public static final bi aH;
    public static final bi aI;
    public static final bi aJ;
    public static final bi aK;
    public static final bi aL;
    public static final bi aM;
    public static final bi aN;
    public static final bi aO;
    public static final bi aP;
    public static final bi aQ;
    public static final bi aR;
    public static final bi aS;
    public static final bi aT;
    public static final bi aU;
    public static final bi aV;
    public static final bi aW;
    public static final bi aX;
    public static final bi aY;
    public static final bi aZ;
    public static final bi ba;
    public static final bi bb;
    public static final bi bc;
    public static final bi bd;
    public static final bi be;
    public static final bi bf;
    public static final bi bg;
    public static final bi bh;
    public static final bi bi;
    public static final bi bj;
    public static final bi bk;
    public static final bi bl;
    public static final bi bm;
    public static final bi bn;
    public static final bi bo;
    public static final bi bp;
    public static final bi bq;
    public static final bi br;
    public static final bi bs;
    public static final bi bt;
    public static final bi bu;
    public static final bi bv;
    public static final bi bw;
    public static final bi bx;
    public static final bi by;
    public static final bi bz;
    public static final bi bA;
    public static final bi bB;
    public static final bi bC;
    public static final bi bD;
    public static final bi bE;
    public static final bi bF;
    public static final bi bG;
    public static final bi bH;
    public static final bi bI;
    public static final bi bJ;
    public static final bi bK;
    public static final bi bL;
    public static final bi bM;
    public static final bi bN;
    public static final bi bO;
    public static final bi bP;
    public static final bi bQ;
    public static final bi bR;
    public static final bi bS;
    public static final bi bT;
    public static final bi bU;
    public static final bi bV;
    public static final bi bW;
    public static final bi bX;
    public static final bi bY;
    public static final bi bZ;
    public static final bi ca;
    public static final bi cb;
    public static final bi cc;
    public static final bi cd;
    public static final bi ce;
    public static final bi cf;
    public static final bi cg;
    public static final bi ch;
    public static final bi ci;
    public static final bi cj;
    public static final bi ck;
    public static final bi cl;
    public static final bi cm;
    public static final bi cn;
    public static final bi co;
    public static final bi cp;
    public static final bi cq;
    public static final bi cr;
    public static final bi cs;
    public static final bi ct;
    public static final bi cu;
    public static final bi cv;
    public static final bi cw;
    public static final bi cx;
    public static final bi cy;
    public static final bi cz;
    public static final bi cA;
    public static final bi cB;
    public static final bi cC;
    public static final bi cD;
    public static final bi cE;
    public static final bi cF;
    public static final bi cG;
    public static final bi cH;
    public static final bi cI;
    public static final bi cJ;
    public static final bi cK;
    public static final bi cL;
    public static final bi cM;
    public static final bi cN;
    public static final bi cO;
    public static final bi cP;
    public static final bi cQ;
    public static final bi cR;
    public static final bi cS;
    public static final bi cT;
    public static final bi cU;
    public static final bi cV;
    public static final bi cW;
    public static final bi cX;
    public static final bi cY;
    public static final bi cZ;
    public static final bi da;
    public static final bi db;
    public static final bi dc;
    public static final bi dd;
    public static final bi de;
    public static final bi df;
    public static final bi dg;
    public static final bi dh;
    public static final bi di;
    public static final bi dj;
    public static final bi dk;
    public static final bi dl;
    public static final bi dm;
    public static final bi dn;
    public static final bi do;
    public static final bi dp;
    public static final bi dq;
    public static final bi dr;
    public static final bi ds;
    public static final bi dt;
    public static final bi du;
    public static final bi dv;
    public static final bi dw;
    public static final bi dx;
    public static final bi dy;
    public static final bi dz;
    public static final bi dA;
    public static final bi dB;
    public static final bi dC;
    public static final bi dD;
    public static final bi dE;
    public static final bi dF;
    public static final bi dG;
    public static final bi dH;
    public static final bi dI;
    public static final bi dJ;
    public static final bi dK;
    public static final bi dL;
    public static final bi dM;
    public static final bi dN;
    public static final bi dO;
    public static final bi dP;
    public static final bi dQ;
    public static final bi dR;
    public static final bi dS;
    public static final bi dT;
    public static final bi dU;
    public static final bi dV;
    public static final bi dW;
    public static final bi dX;
    public static final bi dY;
    public static final bi dZ;
    public static final bi ea;
    public static final bi eb;
    public static final bi ec;
    public static final bi ed;
    public static final bi ee;
    public static final bi ef;
    public static final bi eg;
    public static final bi eh;
    public static final bi ei;
    public static final bi ej;
    public static final bi ek;
    public static final bi el;
    public static final bi em;
    public static final bi en;
    public static final bi eo;
    public static final bi ep;
    public static final bi eq;
    public static final bi er;
    public static final bi es;
    public static final bi et;
    public static final bi eu;
    public static final bi ev;
    public static final bi ew;
    public static final bi ex;
    public static final bi ey;
    public static final bi ez;
    public static final bi eA;
    public static final bi eB;
    public static final bi eC;
    public static final bi eD;
    public static final bi eE;
    public static final bi eF;
    public static final bi eG;
    public static final bi eH;
    public static final bi eI;
    public static final bi eJ;
    public static final bi eK;
    public static final bi eL;
    public static final bi eM;
    public static final bi eN;
    public static final bi eO;
    public static final bi eP;
    public static final bi eQ;
    public static final bi eR;
    public static final bi eS;
    public static final bi eT;
    public static final bi eU;
    public static final bi eV;
    public static final bi eW;
    public static final bi eX;
    public static final bi eY;
    public static final bi eZ;
    public static final bi fa;
    public static final bi fb;
    public static final bi fc;
    public static final bi fd;
    public static final bi fe;
    public static final bi ff;
    public static final bi fg;
    public static final bi fh;
    public static final bi fi;
    public static final bi fj;
    public static final bi fk;
    public static final bi fl;
    public static final bi fm;
    public static final bi fn;
    public static final bi fo;
    public static final bi fp;
    public static final bi fq;
    public static final bi fr;
    public static final bi fs;
    public static final bi ft;
    public static final bi fu;
    public static final bi fv;
    public static final bi fw;
    public static final bi fx;
    public static final bi fy;
    public static final bi fz;
    public static final bi fA;
    public static final bi fB;
    public static final bi fC;
    public static final bi fD;
    public static final bi fE;
    public static final bi fF;
    public static final bi fG;
    public static final bi fH;
    public static final bi fI;
    public static final bi fJ;
    public static final bi fK;
    public static final bi fL;
    public static final bi fM;
    public static final bi fN;
    public static final bi fO;
    public static final bi fP;
    public static final bi fQ;
    public static final bi fR;
    public static final bi fS;
    public static final bi fT;
    public static final bi fU;
    public static final bi fV;
    public static final bi fW;
    public static final bi fX;
    public static final bi fY;
    public static final bi fZ;
    public static final bi ga;
    public static final bi gb;
    public static final bi gc;
    public static final bi gd;
    public static final bi ge;
    public static final bi gf;
    public static final bi gg;
    public static final bi gh;
    public static final bi gi;
    public static final bi gj;
    public static final bi gk;
    public static final bi gl;
    public static final bi gm;
    public static final bi gn;
    public static final bi go;
    public static final bi gp;
    public static final bi gq;
    public static final bi gr;
    public static final bi gs;
    public static final bi gt;
    public static final bi gu;
    public static final bi gv;
    public static final bi gw;
    public static final bi gx;
    public static final bi gy;
    public static final bi gz;
    public static final bi gA;
    public static final bi gB;
    public static final bi gC;
    public static final bi gD;
    public static final bi gE;
    public static final bi gF;
    public static final bi gG;
    public static final bi gH;
    public static final bi gI;
    public static final bi gJ;
    public static final bi gK;
    public static final bi gL;
    public static final bi gM;
    public static final bi gN;
    public static final bi gO;
    public static final bi gP;
    public static final bi gQ;
    public static final bi gR;
    public static final bi gS;
    public static final bi gT;
    public static final bi gU;
    public static final bi gV;
    public static final bi gW;
    public static final bi gX;
    public static final bi gY;
    public static final bi gZ;
    public static final bi ha;
    public static final bi hb;
    public static final bi hc;
    public static final bi hd;
    public static final bi he;
    public static final bi hf;
    public static final bi hg;
    public static final bi hh;
    public static final bi hi;
    public static final bi hj;
    public static final bi hk;
    public static final bi hl;
    public static final bi hm;
    public static final bi hn;
    public static final bi ho;
    public static final bi hp;
    public static final bi hq;
    public static final bi hr;
    public static final bi hs;
    public static final bi ht;
    public static final bi hu;
    public static final bi hv;
    public static final bi hw;
    public static final bi hx;
    public static final bi hy;
    public static final bi hz;
    public static final bi hA;
    public static final bi hB;
    public static final bi hC;
    public static final bi hD;
    public static final bi hE;
    public static final bi hF;
    public static final bi hG;
    public static final bi hH;
    public static final bi hI;
    public static final bi hJ;
    public static final bi hK;
    public static final bi hL;
    public static final bi hM;
    public static final bi hN;
    public static final bi hO;
    public static final bi hP;
    public static final bi hQ;
    public static final bi hR;
    public static final bi hS;
    public static final bi hT;
    public static final bi hU;

    private static bi a(String string) {
        bi bi2 = (bi)bi.a.c(new bpx(string));
        if (bi2 == null) {
            throw new IllegalStateException("Invalid Sound requested: " + string);
        }
        return bi2;
    }

    static {
        if (!bht.a()) {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        }
        a = dah.a("ambient.cave");
        b = dah.a("block.anvil.break");
        c = dah.a("block.anvil.destroy");
        d = dah.a("block.anvil.fall");
        e = dah.a("block.anvil.hit");
        f = dah.a("block.anvil.land");
        g = dah.a("block.anvil.place");
        h = dah.a("block.anvil.step");
        i = dah.a("block.anvil.use");
        j = dah.a("entity.armorstand.break");
        k = dah.a("entity.armorstand.fall");
        l = dah.a("entity.armorstand.hit");
        m = dah.a("entity.armorstand.place");
        n = dah.a("item.armor.equip_chain");
        o = dah.a("item.armor.equip_diamond");
        p = dah.a("item.armor.equip_generic");
        q = dah.a("item.armor.equip_gold");
        r = dah.a("item.armor.equip_iron");
        s = dah.a("item.armor.equip_leather");
        t = dah.a("entity.arrow.hit");
        u = dah.a("entity.arrow.hit_player");
        v = dah.a("entity.arrow.shoot");
        w = dah.a("entity.bat.ambient");
        x = dah.a("entity.bat.death");
        y = dah.a("entity.bat.hurt");
        z = dah.a("entity.bat.loop");
        A = dah.a("entity.bat.takeoff");
        B = dah.a("entity.blaze.ambient");
        C = dah.a("entity.blaze.burn");
        D = dah.a("entity.blaze.death");
        E = dah.a("entity.blaze.hurt");
        F = dah.a("entity.blaze.shoot");
        G = dah.a("entity.bobber.splash");
        H = dah.a("entity.bobber.throw");
        I = dah.a("item.bottle.fill");
        J = dah.a("item.bottle.fill_dragonbreath");
        K = dah.a("block.brewing_stand.brew");
        L = dah.a("item.bucket.empty");
        M = dah.a("item.bucket.empty_lava");
        N = dah.a("item.bucket.fill");
        O = dah.a("item.bucket.fill_lava");
        P = dah.a("entity.cat.ambient");
        Q = dah.a("entity.cat.death");
        R = dah.a("entity.cat.hiss");
        S = dah.a("entity.cat.hurt");
        T = dah.a("entity.cat.purr");
        U = dah.a("entity.cat.purreow");
        V = dah.a("block.chest.close");
        W = dah.a("block.chest.locked");
        X = dah.a("block.chest.open");
        Y = dah.a("entity.chicken.ambient");
        Z = dah.a("entity.chicken.death");
        aa = dah.a("entity.chicken.egg");
        ab = dah.a("entity.chicken.hurt");
        ac = dah.a("entity.chicken.step");
        ad = dah.a("block.chorus_flower.death");
        ae = dah.a("block.chorus_flower.grow");
        af = dah.a("item.chorus_fruit.teleport");
        ag = dah.a("block.cloth.break");
        ah = dah.a("block.cloth.fall");
        ai = dah.a("block.cloth.hit");
        aj = dah.a("block.cloth.place");
        ak = dah.a("block.cloth.step");
        al = dah.a("block.comparator.click");
        am = dah.a("entity.cow.ambient");
        an = dah.a("entity.cow.death");
        ao = dah.a("entity.cow.hurt");
        ap = dah.a("entity.cow.milk");
        aq = dah.a("entity.cow.step");
        ar = dah.a("entity.creeper.death");
        as = dah.a("entity.creeper.hurt");
        at = dah.a("entity.creeper.primed");
        au = dah.a("block.dispenser.dispense");
        av = dah.a("block.dispenser.fail");
        aw = dah.a("block.dispenser.launch");
        ax = dah.a("entity.donkey.ambient");
        ay = dah.a("entity.donkey.angry");
        az = dah.a("entity.donkey.chest");
        aA = dah.a("entity.donkey.death");
        aB = dah.a("entity.donkey.hurt");
        aC = dah.a("entity.egg.throw");
        aD = dah.a("entity.elder_guardian.ambient");
        aE = dah.a("entity.elder_guardian.ambient_land");
        aF = dah.a("entity.elder_guardian.curse");
        aG = dah.a("entity.elder_guardian.death");
        aH = dah.a("entity.elder_guardian.death_land");
        aI = dah.a("entity.elder_guardian.hurt");
        aJ = dah.a("entity.elder_guardian.hurt_land");
        aK = dah.a("item.elytra.flying");
        aL = dah.a("block.enchantment_table.use");
        aM = dah.a("block.enderchest.close");
        aN = dah.a("block.enderchest.open");
        aO = dah.a("entity.enderdragon.ambient");
        aP = dah.a("entity.enderdragon.death");
        aQ = dah.a("entity.enderdragon_fireball.explode");
        aR = dah.a("entity.enderdragon.flap");
        aS = dah.a("entity.enderdragon.growl");
        aT = dah.a("entity.enderdragon.hurt");
        aU = dah.a("entity.enderdragon.shoot");
        aV = dah.a("entity.endereye.launch");
        aW = dah.a("entity.endermen.ambient");
        aX = dah.a("entity.endermen.death");
        aY = dah.a("entity.endermen.hurt");
        aZ = dah.a("entity.endermen.scream");
        ba = dah.a("entity.endermen.stare");
        bb = dah.a("entity.endermen.teleport");
        bc = dah.a("entity.endermite.ambient");
        bd = dah.a("entity.endermite.death");
        be = dah.a("entity.endermite.hurt");
        bf = dah.a("entity.endermite.step");
        bg = dah.a("entity.enderpearl.throw");
        bh = dah.a("block.end_gateway.spawn");
        bi = dah.a("entity.experience_bottle.throw");
        bj = dah.a("entity.experience_orb.pickup");
        bk = dah.a("entity.experience_orb.touch");
        bl = dah.a("block.fence_gate.close");
        bm = dah.a("block.fence_gate.open");
        bn = dah.a("item.firecharge.use");
        bo = dah.a("entity.firework.blast");
        bp = dah.a("entity.firework.blast_far");
        bq = dah.a("entity.firework.large_blast");
        br = dah.a("entity.firework.large_blast_far");
        bs = dah.a("entity.firework.launch");
        bt = dah.a("entity.firework.shoot");
        bu = dah.a("entity.firework.twinkle");
        bv = dah.a("entity.firework.twinkle_far");
        bw = dah.a("block.fire.ambient");
        bx = dah.a("block.fire.extinguish");
        by = dah.a("item.flintandsteel.use");
        bz = dah.a("block.furnace.fire_crackle");
        bA = dah.a("entity.generic.big_fall");
        bB = dah.a("entity.generic.burn");
        bC = dah.a("entity.generic.death");
        bD = dah.a("entity.generic.drink");
        bE = dah.a("entity.generic.eat");
        bF = dah.a("entity.generic.explode");
        bG = dah.a("entity.generic.extinguish_fire");
        bH = dah.a("entity.generic.hurt");
        bI = dah.a("entity.generic.small_fall");
        bJ = dah.a("entity.generic.splash");
        bK = dah.a("entity.generic.swim");
        bL = dah.a("entity.ghast.ambient");
        bM = dah.a("entity.ghast.death");
        bN = dah.a("entity.ghast.hurt");
        bO = dah.a("entity.ghast.scream");
        bP = dah.a("entity.ghast.shoot");
        bQ = dah.a("entity.ghast.warn");
        bR = dah.a("block.glass.break");
        bS = dah.a("block.glass.fall");
        bT = dah.a("block.glass.hit");
        bU = dah.a("block.glass.place");
        bV = dah.a("block.glass.step");
        bW = dah.a("block.grass.break");
        bX = dah.a("block.grass.fall");
        bY = dah.a("block.grass.hit");
        bZ = dah.a("block.grass.place");
        ca = dah.a("block.grass.step");
        cb = dah.a("block.gravel.break");
        cc = dah.a("block.gravel.fall");
        cd = dah.a("block.gravel.hit");
        ce = dah.a("block.gravel.place");
        cf = dah.a("block.gravel.step");
        cg = dah.a("entity.guardian.ambient");
        ch = dah.a("entity.guardian.ambient_land");
        ci = dah.a("entity.guardian.attack");
        cj = dah.a("entity.guardian.death");
        ck = dah.a("entity.guardian.death_land");
        cl = dah.a("entity.guardian.flop");
        cm = dah.a("entity.guardian.hurt");
        cn = dah.a("entity.guardian.hurt_land");
        co = dah.a("item.hoe.till");
        cp = dah.a("entity.horse.ambient");
        cq = dah.a("entity.horse.angry");
        cr = dah.a("entity.horse.armor");
        cs = dah.a("entity.horse.breathe");
        ct = dah.a("entity.horse.death");
        cu = dah.a("entity.horse.eat");
        cv = dah.a("entity.horse.gallop");
        cw = dah.a("entity.horse.hurt");
        cx = dah.a("entity.horse.jump");
        cy = dah.a("entity.horse.land");
        cz = dah.a("entity.horse.saddle");
        cA = dah.a("entity.horse.step");
        cB = dah.a("entity.horse.step_wood");
        cC = dah.a("entity.hostile.big_fall");
        cD = dah.a("entity.hostile.death");
        cE = dah.a("entity.hostile.hurt");
        cF = dah.a("entity.hostile.small_fall");
        cG = dah.a("entity.hostile.splash");
        cH = dah.a("entity.hostile.swim");
        cI = dah.a("entity.husk.ambient");
        cJ = dah.a("entity.husk.death");
        cK = dah.a("entity.husk.hurt");
        cL = dah.a("entity.husk.step");
        cM = dah.a("entity.irongolem.attack");
        cN = dah.a("entity.irongolem.death");
        cO = dah.a("entity.irongolem.hurt");
        cP = dah.a("entity.irongolem.step");
        cQ = dah.a("block.iron_door.close");
        cR = dah.a("block.iron_door.open");
        cS = dah.a("block.iron_trapdoor.close");
        cT = dah.a("block.iron_trapdoor.open");
        cU = dah.a("entity.itemframe.add_item");
        cV = dah.a("entity.itemframe.break");
        cW = dah.a("entity.itemframe.place");
        cX = dah.a("entity.itemframe.remove_item");
        cY = dah.a("entity.itemframe.rotate_item");
        cZ = dah.a("entity.item.break");
        da = dah.a("entity.item.pickup");
        db = dah.a("block.ladder.break");
        dc = dah.a("block.ladder.fall");
        dd = dah.a("block.ladder.hit");
        de = dah.a("block.ladder.place");
        df = dah.a("block.ladder.step");
        dg = dah.a("block.lava.ambient");
        dh = dah.a("block.lava.extinguish");
        di = dah.a("block.lava.pop");
        dj = dah.a("entity.leashknot.break");
        dk = dah.a("entity.leashknot.place");
        dl = dah.a("block.lever.click");
        dm = dah.a("entity.lightning.impact");
        dn = dah.a("entity.lightning.thunder");
        do = dah.a("entity.lingeringpotion.throw");
        dp = dah.a("entity.magmacube.death");
        dq = dah.a("entity.magmacube.hurt");
        dr = dah.a("entity.magmacube.jump");
        ds = dah.a("entity.magmacube.squish");
        dt = dah.a("block.metal.break");
        du = dah.a("block.metal.fall");
        dv = dah.a("block.metal.hit");
        dw = dah.a("block.metal.place");
        dx = dah.a("block.metal_pressureplate.click_off");
        dy = dah.a("block.metal_pressureplate.click_on");
        dz = dah.a("block.metal.step");
        dA = dah.a("entity.minecart.inside");
        dB = dah.a("entity.minecart.riding");
        dC = dah.a("entity.mooshroom.shear");
        dD = dah.a("entity.mule.ambient");
        dE = dah.a("entity.mule.death");
        dF = dah.a("entity.mule.hurt");
        dG = dah.a("music.creative");
        dH = dah.a("music.credits");
        dI = dah.a("music.dragon");
        dJ = dah.a("music.end");
        dK = dah.a("music.game");
        dL = dah.a("music.menu");
        dM = dah.a("music.nether");
        dN = dah.a("block.note.basedrum");
        dO = dah.a("block.note.bass");
        dP = dah.a("block.note.harp");
        dQ = dah.a("block.note.hat");
        dR = dah.a("block.note.pling");
        dS = dah.a("block.note.snare");
        dT = dah.a("entity.painting.break");
        dU = dah.a("entity.painting.place");
        dV = dah.a("entity.pig.ambient");
        dW = dah.a("entity.pig.death");
        dX = dah.a("entity.pig.hurt");
        dY = dah.a("entity.pig.saddle");
        dZ = dah.a("entity.pig.step");
        ea = dah.a("block.piston.contract");
        eb = dah.a("block.piston.extend");
        ec = dah.a("entity.player.attack.crit");
        ed = dah.a("entity.player.attack.knockback");
        ee = dah.a("entity.player.attack.nodamage");
        ef = dah.a("entity.player.attack.strong");
        eg = dah.a("entity.player.attack.sweep");
        eh = dah.a("entity.player.attack.weak");
        ei = dah.a("entity.player.big_fall");
        ej = dah.a("entity.player.breath");
        ek = dah.a("entity.player.burp");
        el = dah.a("entity.player.death");
        em = dah.a("entity.player.hurt");
        en = dah.a("entity.player.levelup");
        eo = dah.a("entity.player.small_fall");
        ep = dah.a("entity.player.splash");
        eq = dah.a("entity.player.swim");
        er = dah.a("entity.polar_bear.ambient");
        es = dah.a("entity.polar_bear.baby_ambient");
        et = dah.a("entity.polar_bear.death");
        eu = dah.a("entity.polar_bear.hurt");
        ev = dah.a("entity.polar_bear.step");
        ew = dah.a("entity.polar_bear.warning");
        ex = dah.a("block.portal.ambient");
        ey = dah.a("block.portal.travel");
        ez = dah.a("block.portal.trigger");
        eA = dah.a("entity.rabbit.ambient");
        eB = dah.a("entity.rabbit.attack");
        eC = dah.a("entity.rabbit.death");
        eD = dah.a("entity.rabbit.hurt");
        eE = dah.a("entity.rabbit.jump");
        eF = dah.a("record.11");
        eG = dah.a("record.13");
        eH = dah.a("record.blocks");
        eI = dah.a("record.cat");
        eJ = dah.a("record.chirp");
        eK = dah.a("record.far");
        eL = dah.a("record.mall");
        eM = dah.a("record.mellohi");
        eN = dah.a("record.stal");
        eO = dah.a("record.strad");
        eP = dah.a("record.wait");
        eQ = dah.a("record.ward");
        eR = dah.a("block.redstone_torch.burnout");
        eS = dah.a("block.sand.break");
        eT = dah.a("block.sand.fall");
        eU = dah.a("block.sand.hit");
        eV = dah.a("block.sand.place");
        eW = dah.a("block.sand.step");
        eX = dah.a("entity.sheep.ambient");
        eY = dah.a("entity.sheep.death");
        eZ = dah.a("entity.sheep.hurt");
        fa = dah.a("entity.sheep.shear");
        fb = dah.a("entity.sheep.step");
        fc = dah.a("item.shield.block");
        fd = dah.a("item.shield.break");
        fe = dah.a("item.shovel.flatten");
        ff = dah.a("entity.shulker.ambient");
        fg = dah.a("entity.shulker_bullet.hit");
        fh = dah.a("entity.shulker_bullet.hurt");
        fi = dah.a("entity.shulker.close");
        fj = dah.a("entity.shulker.death");
        fk = dah.a("entity.shulker.hurt");
        fl = dah.a("entity.shulker.hurt_closed");
        fm = dah.a("entity.shulker.open");
        fn = dah.a("entity.shulker.shoot");
        fo = dah.a("entity.shulker.teleport");
        fp = dah.a("entity.silverfish.ambient");
        fq = dah.a("entity.silverfish.death");
        fr = dah.a("entity.silverfish.hurt");
        fs = dah.a("entity.silverfish.step");
        ft = dah.a("entity.skeleton.ambient");
        fu = dah.a("entity.skeleton.death");
        fv = dah.a("entity.skeleton_horse.ambient");
        fw = dah.a("entity.skeleton_horse.death");
        fx = dah.a("entity.skeleton_horse.hurt");
        fy = dah.a("entity.skeleton.hurt");
        fz = dah.a("entity.skeleton.shoot");
        fA = dah.a("entity.skeleton.step");
        fB = dah.a("entity.slime.attack");
        fC = dah.a("block.slime.break");
        fD = dah.a("entity.slime.death");
        fE = dah.a("block.slime.fall");
        fF = dah.a("block.slime.hit");
        fG = dah.a("entity.slime.hurt");
        fH = dah.a("entity.slime.jump");
        fI = dah.a("block.slime.place");
        fJ = dah.a("entity.slime.squish");
        fK = dah.a("block.slime.step");
        fL = dah.a("entity.small_magmacube.death");
        fM = dah.a("entity.small_magmacube.hurt");
        fN = dah.a("entity.small_magmacube.squish");
        fO = dah.a("entity.small_slime.death");
        fP = dah.a("entity.small_slime.hurt");
        fQ = dah.a("entity.small_slime.jump");
        fR = dah.a("entity.small_slime.squish");
        fS = dah.a("entity.snowball.throw");
        fT = dah.a("entity.snowman.ambient");
        fU = dah.a("entity.snowman.death");
        fV = dah.a("entity.snowman.hurt");
        fW = dah.a("entity.snowman.shoot");
        fX = dah.a("block.snow.break");
        fY = dah.a("block.snow.fall");
        fZ = dah.a("block.snow.hit");
        ga = dah.a("block.snow.place");
        gb = dah.a("block.snow.step");
        gc = dah.a("entity.spider.ambient");
        gd = dah.a("entity.spider.death");
        ge = dah.a("entity.spider.hurt");
        gf = dah.a("entity.spider.step");
        gg = dah.a("entity.splash_potion.break");
        gh = dah.a("entity.splash_potion.throw");
        gi = dah.a("entity.squid.ambient");
        gj = dah.a("entity.squid.death");
        gk = dah.a("entity.squid.hurt");
        gl = dah.a("block.stone.break");
        gm = dah.a("block.stone_button.click_off");
        gn = dah.a("block.stone_button.click_on");
        go = dah.a("block.stone.fall");
        gp = dah.a("block.stone.hit");
        gq = dah.a("block.stone.place");
        gr = dah.a("block.stone_pressureplate.click_off");
        gs = dah.a("block.stone_pressureplate.click_on");
        gt = dah.a("block.stone.step");
        gu = dah.a("entity.stray.ambient");
        gv = dah.a("entity.stray.death");
        gw = dah.a("entity.stray.hurt");
        gx = dah.a("entity.stray.step");
        gy = dah.a("enchant.thorns.hit");
        gz = dah.a("entity.tnt.primed");
        gA = dah.a("block.tripwire.attach");
        gB = dah.a("block.tripwire.click_off");
        gC = dah.a("block.tripwire.click_on");
        gD = dah.a("block.tripwire.detach");
        gE = dah.a("ui.button.click");
        gF = dah.a("entity.villager.ambient");
        gG = dah.a("entity.villager.death");
        gH = dah.a("entity.villager.hurt");
        gI = dah.a("entity.villager.no");
        gJ = dah.a("entity.villager.trading");
        gK = dah.a("entity.villager.yes");
        gL = dah.a("block.waterlily.place");
        gM = dah.a("block.water.ambient");
        gN = dah.a("weather.rain");
        gO = dah.a("weather.rain.above");
        gP = dah.a("entity.witch.ambient");
        gQ = dah.a("entity.witch.death");
        gR = dah.a("entity.witch.drink");
        gS = dah.a("entity.witch.hurt");
        gT = dah.a("entity.witch.throw");
        gU = dah.a("entity.wither.ambient");
        gV = dah.a("entity.wither.break_block");
        gW = dah.a("entity.wither.death");
        gX = dah.a("entity.wither.hurt");
        gY = dah.a("entity.wither.shoot");
        gZ = dah.a("entity.wither.spawn");
        ha = dah.a("entity.wither_skeleton.ambient");
        hb = dah.a("entity.wither_skeleton.death");
        hc = dah.a("entity.wither_skeleton.hurt");
        hd = dah.a("entity.wither_skeleton.step");
        he = dah.a("entity.wolf.ambient");
        hf = dah.a("entity.wolf.death");
        hg = dah.a("entity.wolf.growl");
        hh = dah.a("entity.wolf.howl");
        hi = dah.a("entity.wolf.hurt");
        hj = dah.a("entity.wolf.pant");
        hk = dah.a("entity.wolf.shake");
        hl = dah.a("entity.wolf.step");
        hm = dah.a("entity.wolf.whine");
        hn = dah.a("block.wooden_door.close");
        ho = dah.a("block.wooden_door.open");
        hp = dah.a("block.wooden_trapdoor.close");
        hq = dah.a("block.wooden_trapdoor.open");
        hr = dah.a("block.wood.break");
        hs = dah.a("block.wood_button.click_off");
        ht = dah.a("block.wood_button.click_on");
        hu = dah.a("block.wood.fall");
        hv = dah.a("block.wood.hit");
        hw = dah.a("block.wood.place");
        hx = dah.a("block.wood_pressureplate.click_off");
        hy = dah.a("block.wood_pressureplate.click_on");
        hz = dah.a("block.wood.step");
        hA = dah.a("entity.zombie.ambient");
        hB = dah.a("entity.zombie.attack_door_wood");
        hC = dah.a("entity.zombie.attack_iron_door");
        hD = dah.a("entity.zombie.break_door_wood");
        hE = dah.a("entity.zombie.death");
        hF = dah.a("entity.zombie_horse.ambient");
        hG = dah.a("entity.zombie_horse.death");
        hH = dah.a("entity.zombie_horse.hurt");
        hI = dah.a("entity.zombie.hurt");
        hJ = dah.a("entity.zombie.infect");
        hK = dah.a("entity.zombie_pig.ambient");
        hL = dah.a("entity.zombie_pig.angry");
        hM = dah.a("entity.zombie_pig.death");
        hN = dah.a("entity.zombie_pig.hurt");
        hO = dah.a("entity.zombie.step");
        hP = dah.a("entity.zombie_villager.ambient");
        hQ = dah.a("entity.zombie_villager.converted");
        hR = dah.a("entity.zombie_villager.cure");
        hS = dah.a("entity.zombie_villager.death");
        hT = dah.a("entity.zombie_villager.hurt");
        hU = dah.a("entity.zombie_villager.step");
    }
}

