/*
 * Decompiled with CFR 0.150.
 */
public class dw {
    public final float a;
    public final float b;
    public final float c;
    public final float d;
    public final float e;
    public final float f;
    public final float g;
    public final float h;
    public final float i;
    public final float j;
    public final float k;
    public final float l;
    public final float m;
    public final float n;
    public final float o;
    public final float p;
    public final int q;
    public final boolean r;
    public final boolean s;
    public final int t;
    public final boolean u;
    public final boolean v;
    public final boolean w;
    public final boolean x;
    public final boolean y;
    public final boolean z;
    public final boolean A;
    public final int B;
    public final boolean C;
    public final int D;
    public final boolean E;
    public final int F;
    public final int G;
    public final int H;
    public final int I;
    public final int J;
    public final int K;
    public final int L;
    public final int M;
    public final int N;
    public final int O;
    public final int P;
    public final int Q;
    public final int R;
    public final int S;
    public final int T;
    public final int U;
    public final int V;
    public final int W;
    public final int X;
    public final int Y;
    public final int Z;
    public final int aa;
    public final int ab;
    public final int ac;
    public final int ad;
    public final int ae;
    public final int af;
    public final int ag;
    public final int ah;
    public final int ai;
    public final int aj;
    public final int ak;
    public final int al;
    public final int am;
    public final int an;
    public final int ao;
    public final int ap;
    public final int aq;
    public final int ar;
    public final int as;
    public final int at;
    public final int au;
    public final int av;
    public final int aw;
    public final int ax;
    public final int ay;
    public final int az;

    private dw(bqr bqr2) {
        this.a = bqr2.b;
        this.b = bqr2.c;
        this.c = bqr2.d;
        this.d = bqr2.e;
        this.e = bqr2.f;
        this.f = bqr2.g;
        this.g = bqr2.h;
        this.h = bqr2.i;
        this.i = bqr2.j;
        this.j = bqr2.k;
        this.k = bqr2.l;
        this.l = bqr2.m;
        this.m = bqr2.n;
        this.n = bqr2.o;
        this.o = bqr2.p;
        this.p = bqr2.q;
        this.q = bqr2.r;
        this.r = bqr2.s;
        this.s = bqr2.t;
        this.t = bqr2.u;
        this.u = bqr2.v;
        this.v = bqr2.w;
        this.w = bqr2.x;
        this.x = bqr2.y;
        this.y = bqr2.z;
        this.z = bqr2.A;
        this.A = bqr2.B;
        this.B = bqr2.C;
        this.C = bqr2.D;
        this.D = bqr2.E;
        this.E = bqr2.F;
        this.F = bqr2.G;
        this.G = bqr2.H;
        this.H = bqr2.I;
        this.I = bqr2.J;
        this.J = bqr2.K;
        this.K = bqr2.L;
        this.L = bqr2.M;
        this.M = bqr2.N;
        this.N = bqr2.O;
        this.O = bqr2.P;
        this.P = bqr2.Q;
        this.Q = bqr2.R;
        this.R = bqr2.S;
        this.S = bqr2.T;
        this.T = bqr2.U;
        this.U = bqr2.V;
        this.V = bqr2.W;
        this.W = bqr2.X;
        this.X = bqr2.Y;
        this.Y = bqr2.Z;
        this.Z = bqr2.aa;
        this.aa = bqr2.ab;
        this.ab = bqr2.ac;
        this.ac = bqr2.ad;
        this.ad = bqr2.ae;
        this.ae = bqr2.af;
        this.af = bqr2.ag;
        this.ag = bqr2.ah;
        this.ah = bqr2.ai;
        this.ai = bqr2.aj;
        this.aj = bqr2.ak;
        this.ak = bqr2.al;
        this.al = bqr2.am;
        this.am = bqr2.an;
        this.an = bqr2.ao;
        this.ao = bqr2.ap;
        this.ap = bqr2.aq;
        this.aq = bqr2.ar;
        this.ar = bqr2.as;
        this.as = bqr2.at;
        this.at = bqr2.au;
        this.au = bqr2.av;
        this.av = bqr2.aw;
        this.aw = bqr2.ax;
        this.ax = bqr2.ay;
        this.ay = bqr2.az;
        this.az = bqr2.aA;
    }

    /* synthetic */ dw(bqr bqr2, cfx cfx2) {
        this(bqr2);
    }
}

