/*
 * Decompiled with CFR 0.150.
 */
public class hp {
    public static final azg a;
    public static final azg b;
    public static final azg c;
    public static final azg d;
    public static final azg e;
    public static final azd f;
    public static final azg g;
    public static final azg h;
    public static final azg i;
    public static final azg j;
    public static final azg k;
    public static final azg l;
    public static final azg m;
    public static final azg n;
    public static final azg o;
    public static final azg p;
    public static final azg q;
    public static final azg r;
    public static final azg s;
    public static final azg t;
    public static final azg u;
    public static final azg v;
    public static final azg w;
    public static final azg x;
    public static final azg y;
    public static final azg z;
    public static final azg A;
    public static final azg B;
    public static final azg C;
    public static final azg D;
    public static final azg E;
    public static final azg F;
    public static final azg G;
    public static final azg H;
    public static final azg I;
    public static final azg J;
    public static final azg K;
    public static final azg L;
    public static final azg M;
    public static final azg N;
    public static final azg O;
    public static final azg P;
    public static final azg Q;
    public static final azg R;
    public static final uh S;
    public static final uh T;
    public static final uh U;
    public static final uh V;
    public static final uh W;
    public static final uh X;
    public static final uh Y;
    public static final uh Z;
    public static final uh aa;
    public static final uh ab;
    public static final uh ac;
    public static final uh ad;
    public static final uh ae;
    public static final uh af;
    public static final uh ag;
    public static final uh ah;
    public static final uh ai;
    public static final uh aj;
    public static final uh ak;
    public static final uh al;
    public static final azg am;
    public static final azg an;
    public static final azg ao;
    public static final azg ap;
    public static final azg aq;
    public static final azg ar;
    public static final azg as;
    public static final azg at;
    public static final azg au;
    public static final azg av;
    public static final azg aw;
    public static final azg ax;
    public static final azg ay;
    public static final azg az;
    public static final azg aA;
    public static final azg aB;
    public static final azg aC;
    public static final azg aD;
    public static final azg aE;
    public static final azg aF;
    public static final azg aG;
    public static final azg aH;
    public static final azg aI;
    public static final azg aJ;
    public static final azg aK;
    public static final azg aL;
    public static final azg aM;
    public static final azg aN;
    public static final azg aO;
    public static final azg aP;
    public static final azg aQ;
    public static final azg aR;
    public static final azg aS;
    public static final azg aT;
    public static final azg aU;
    public static final azg aV;
    public static final azg aW;
    public static final azg aX;
    public static final bic aY;
    public static final azg aZ;
    public static final azg ba;
    public static final azg bb;
    public static final azg bc;
    public static final azg bd;
    public static final azg be;
    public static final azg bf;
    public static final azg bg;
    public static final azg bh;
    public static final azg bi;
    public static final azg bj;
    public static final ayb bk;
    public static final blf bl;
    public static final azg bm;
    public static final azg bn;
    public static final azg bo;
    public static final azg bp;
    public static final azg bq;
    public static final azg br;
    public static final azg bs;
    public static final azg bt;
    public static final azg bu;
    public static final azg bv;
    public static final azg bw;
    public static final azg bx;
    public static final azg by;
    public static final azg bz;
    public static final azg bA;
    public static final azg bB;
    public static final azg bC;
    public static final azg bD;
    public static final azg bE;
    public static final azg bF;
    public static final abb bG;
    public static final abb bH;
    public static final abb bI;
    public static final azg bJ;
    public static final azg bK;
    public static final azg bL;
    public static final azg bM;
    public static final azg bN;
    public static final azg bO;
    public static final azg bP;
    public static final azg bQ;
    public static final azg bR;
    public static final azg bS;
    public static final azg bT;
    public static final azg bU;
    public static final azg bV;
    public static final azg bW;
    public static final azg bX;
    public static final azg bY;
    public static final azg bZ;
    public static final azg ca;
    public static final azg cb;
    public static final azg cc;
    public static final azg cd;
    public static final azg ce;
    public static final dgh cf;
    public static final azg cg;
    public static final azg ch;
    public static final azg ci;
    public static final azg cj;
    public static final azg ck;
    public static final azg cl;
    public static final azg cm;
    public static final auj cn;
    public static final azg co;
    public static final azg cp;
    public static final azg cq;
    public static final azg cr;
    public static final azg cs;
    public static final nq ct;
    public static final azg cu;
    public static final azg cv;
    public static final azg cw;
    public static final azg cx;
    public static final azg cy;
    public static final azg cz;
    public static final azg cA;
    public static final azg cB;
    public static final azg cC;
    public static final azg cD;
    public static final azg cE;
    public static final azg cF;
    public static final azg cG;
    public static final azg cH;
    public static final azg cI;
    public static final azg cJ;
    public static final azg cK;
    public static final azg cL;
    public static final azg cM;
    public static final azg cN;
    public static final azg cO;
    public static final azg cP;
    public static final azg cQ;
    public static final azg cR;
    public static final azg cS;
    public static final azg cT;
    public static final azg cU;
    public static final azg cV;
    public static final azg cW;

    private static azg a(String string) {
        azg azg2 = (azg)azg.g.c(new bpx(string));
        if (azg2 == null) {
            throw new IllegalStateException("Invalid Item requested: " + string);
        }
        return azg2;
    }

    static {
        if (!bht.a()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        a = hp.a("iron_shovel");
        b = hp.a("iron_pickaxe");
        c = hp.a("iron_axe");
        d = hp.a("flint_and_steel");
        e = hp.a("apple");
        f = (azd)hp.a("bow");
        g = hp.a("arrow");
        h = hp.a("spectral_arrow");
        i = hp.a("tipped_arrow");
        j = hp.a("coal");
        k = hp.a("diamond");
        l = hp.a("iron_ingot");
        m = hp.a("gold_ingot");
        n = hp.a("iron_sword");
        o = hp.a("wooden_sword");
        p = hp.a("wooden_shovel");
        q = hp.a("wooden_pickaxe");
        r = hp.a("wooden_axe");
        s = hp.a("stone_sword");
        t = hp.a("stone_shovel");
        u = hp.a("stone_pickaxe");
        v = hp.a("stone_axe");
        w = hp.a("diamond_sword");
        x = hp.a("diamond_shovel");
        y = hp.a("diamond_pickaxe");
        z = hp.a("diamond_axe");
        A = hp.a("stick");
        B = hp.a("bowl");
        C = hp.a("mushroom_stew");
        D = hp.a("golden_sword");
        E = hp.a("golden_shovel");
        F = hp.a("golden_pickaxe");
        G = hp.a("golden_axe");
        H = hp.a("string");
        I = hp.a("feather");
        J = hp.a("gunpowder");
        K = hp.a("wooden_hoe");
        L = hp.a("stone_hoe");
        M = hp.a("iron_hoe");
        N = hp.a("diamond_hoe");
        O = hp.a("golden_hoe");
        P = hp.a("wheat_seeds");
        Q = hp.a("wheat");
        R = hp.a("bread");
        S = (uh)hp.a("leather_helmet");
        T = (uh)hp.a("leather_chestplate");
        U = (uh)hp.a("leather_leggings");
        V = (uh)hp.a("leather_boots");
        W = (uh)hp.a("chainmail_helmet");
        X = (uh)hp.a("chainmail_chestplate");
        Y = (uh)hp.a("chainmail_leggings");
        Z = (uh)hp.a("chainmail_boots");
        aa = (uh)hp.a("iron_helmet");
        ab = (uh)hp.a("iron_chestplate");
        ac = (uh)hp.a("iron_leggings");
        ad = (uh)hp.a("iron_boots");
        ae = (uh)hp.a("diamond_helmet");
        af = (uh)hp.a("diamond_chestplate");
        ag = (uh)hp.a("diamond_leggings");
        ah = (uh)hp.a("diamond_boots");
        ai = (uh)hp.a("golden_helmet");
        aj = (uh)hp.a("golden_chestplate");
        ak = (uh)hp.a("golden_leggings");
        al = (uh)hp.a("golden_boots");
        am = hp.a("flint");
        an = hp.a("porkchop");
        ao = hp.a("cooked_porkchop");
        ap = hp.a("painting");
        aq = hp.a("golden_apple");
        ar = hp.a("sign");
        as = hp.a("wooden_door");
        at = hp.a("spruce_door");
        au = hp.a("birch_door");
        av = hp.a("jungle_door");
        aw = hp.a("acacia_door");
        ax = hp.a("dark_oak_door");
        ay = hp.a("bucket");
        az = hp.a("water_bucket");
        aA = hp.a("lava_bucket");
        aB = hp.a("minecart");
        aC = hp.a("saddle");
        aD = hp.a("iron_door");
        aE = hp.a("redstone");
        aF = hp.a("snowball");
        aG = hp.a("boat");
        aH = hp.a("spruce_boat");
        aI = hp.a("birch_boat");
        aJ = hp.a("jungle_boat");
        aK = hp.a("acacia_boat");
        aL = hp.a("dark_oak_boat");
        aM = hp.a("leather");
        aN = hp.a("milk_bucket");
        aO = hp.a("brick");
        aP = hp.a("clay_ball");
        aQ = hp.a("reeds");
        aR = hp.a("paper");
        aS = hp.a("book");
        aT = hp.a("slime_ball");
        aU = hp.a("chest_minecart");
        aV = hp.a("furnace_minecart");
        aW = hp.a("egg");
        aX = hp.a("compass");
        aY = (bic)hp.a("fishing_rod");
        aZ = hp.a("clock");
        ba = hp.a("glowstone_dust");
        bb = hp.a("fish");
        bc = hp.a("cooked_fish");
        bd = hp.a("dye");
        be = hp.a("bone");
        bf = hp.a("sugar");
        bg = hp.a("cake");
        bh = hp.a("bed");
        bi = hp.a("repeater");
        bj = hp.a("cookie");
        bk = (ayb)hp.a("filled_map");
        bl = (blf)hp.a("shears");
        bm = hp.a("melon");
        bn = hp.a("pumpkin_seeds");
        bo = hp.a("melon_seeds");
        bp = hp.a("beef");
        bq = hp.a("cooked_beef");
        br = hp.a("chicken");
        bs = hp.a("cooked_chicken");
        bt = hp.a("mutton");
        bu = hp.a("cooked_mutton");
        bv = hp.a("rabbit");
        bw = hp.a("cooked_rabbit");
        bx = hp.a("rabbit_stew");
        by = hp.a("rabbit_foot");
        bz = hp.a("rabbit_hide");
        bA = hp.a("rotten_flesh");
        bB = hp.a("ender_pearl");
        bC = hp.a("blaze_rod");
        bD = hp.a("ghast_tear");
        bE = hp.a("gold_nugget");
        bF = hp.a("nether_wart");
        bG = (abb)hp.a("potion");
        bH = (abb)hp.a("splash_potion");
        bI = (abb)hp.a("lingering_potion");
        bJ = hp.a("glass_bottle");
        bK = hp.a("dragon_breath");
        bL = hp.a("spider_eye");
        bM = hp.a("fermented_spider_eye");
        bN = hp.a("blaze_powder");
        bO = hp.a("magma_cream");
        bP = hp.a("brewing_stand");
        bQ = hp.a("cauldron");
        bR = hp.a("ender_eye");
        bS = hp.a("speckled_melon");
        bT = hp.a("spawn_egg");
        bU = hp.a("experience_bottle");
        bV = hp.a("fire_charge");
        bW = hp.a("writable_book");
        bX = hp.a("written_book");
        bY = hp.a("emerald");
        bZ = hp.a("item_frame");
        ca = hp.a("flower_pot");
        cb = hp.a("carrot");
        cc = hp.a("potato");
        cd = hp.a("baked_potato");
        ce = hp.a("poisonous_potato");
        cf = (dgh)hp.a("map");
        cg = hp.a("golden_carrot");
        ch = hp.a("skull");
        ci = hp.a("carrot_on_a_stick");
        cj = hp.a("nether_star");
        ck = hp.a("pumpkin_pie");
        cl = hp.a("fireworks");
        cm = hp.a("firework_charge");
        cn = (auj)hp.a("enchanted_book");
        co = hp.a("comparator");
        cp = hp.a("netherbrick");
        cq = hp.a("quartz");
        cr = hp.a("tnt_minecart");
        cs = hp.a("hopper_minecart");
        ct = (nq)hp.a("armor_stand");
        cu = hp.a("iron_horse_armor");
        cv = hp.a("golden_horse_armor");
        cw = hp.a("diamond_horse_armor");
        cx = hp.a("lead");
        cy = hp.a("name_tag");
        cz = hp.a("command_block_minecart");
        cA = hp.a("record_13");
        cB = hp.a("record_cat");
        cC = hp.a("record_blocks");
        cD = hp.a("record_chirp");
        cE = hp.a("record_far");
        cF = hp.a("record_mall");
        cG = hp.a("record_mellohi");
        cH = hp.a("record_stal");
        cI = hp.a("record_strad");
        cJ = hp.a("record_ward");
        cK = hp.a("record_11");
        cL = hp.a("record_wait");
        cM = hp.a("prismarine_shard");
        cN = hp.a("prismarine_crystals");
        cO = hp.a("banner");
        cP = hp.a("end_crystal");
        cQ = hp.a("shield");
        cR = hp.a("elytra");
        cS = hp.a("chorus_fruit");
        cT = hp.a("chorus_fruit_popped");
        cU = hp.a("beetroot_seeds");
        cV = hp.a("beetroot");
        cW = hp.a("beetroot_soup");
    }
}

