/*
 * Decompiled with CFR 0.150.
 */
package net.java.games.input;

import net.java.games.input.l;

public class o
extends l {
    public static final o a = new o("Void");
    public static final o b = new o("Escape");
    public static final o c = new o("1");
    public static final o d = new o("2");
    public static final o e = new o("3");
    public static final o f = new o("4");
    public static final o g = new o("5");
    public static final o h = new o("6");
    public static final o i = new o("7");
    public static final o j = new o("8");
    public static final o k = new o("9");
    public static final o l = new o("0");
    public static final o m = new o("-");
    public static final o n = new o("=");
    public static final o o = new o("Back");
    public static final o p = new o("Tab");
    public static final o q = new o("Q");
    public static final o r = new o("W");
    public static final o s = new o("E");
    public static final o t = new o("R");
    public static final o u = new o("T");
    public static final o v = new o("Y");
    public static final o w = new o("U");
    public static final o x = new o("I");
    public static final o y = new o("O");
    public static final o z = new o("P");
    public static final o A = new o("[");
    public static final o B = new o("]");
    public static final o C = new o("Return");
    public static final o D = new o("Left Control");
    public static final o E = new o("A");
    public static final o F = new o("S");
    public static final o G = new o("D");
    public static final o H = new o("F");
    public static final o I = new o("G");
    public static final o J = new o("H");
    public static final o K = new o("J");
    public static final o L = new o("K");
    public static final o M = new o("L");
    public static final o N = new o(";");
    public static final o O = new o("'");
    public static final o P = new o("~");
    public static final o Q = new o("Left Shift");
    public static final o R = new o("\\");
    public static final o S = new o("Z");
    public static final o T = new o("X");
    public static final o U = new o("C");
    public static final o V = new o("V");
    public static final o W = new o("B");
    public static final o X = new o("N");
    public static final o Y = new o("M");
    public static final o Z = new o(",");
    public static final o aa = new o(".");
    public static final o ab = new o("/");
    public static final o ac = new o("Right Shift");
    public static final o ad = new o("Multiply");
    public static final o ae = new o("Left Alt");
    public static final o af = new o(" ");
    public static final o ag = new o("Caps Lock");
    public static final o ah = new o("F1");
    public static final o ai = new o("F2");
    public static final o aj = new o("F3");
    public static final o ak = new o("F4");
    public static final o al = new o("F5");
    public static final o am = new o("F6");
    public static final o an = new o("F7");
    public static final o ao = new o("F8");
    public static final o ap = new o("F9");
    public static final o aq = new o("F10");
    public static final o ar = new o("Num Lock");
    public static final o as = new o("Scroll Lock");
    public static final o at = new o("Num 7");
    public static final o au = new o("Num 8");
    public static final o av = new o("Num 9");
    public static final o aw = new o("Num -");
    public static final o ax = new o("Num 4");
    public static final o ay = new o("Num 5");
    public static final o az = new o("Num 6");
    public static final o aA = new o("Num +");
    public static final o aB = new o("Num 1");
    public static final o aC = new o("Num 2");
    public static final o aD = new o("Num 3");
    public static final o aE = new o("Num 0");
    public static final o aF = new o("Num .");
    public static final o aG = new o("F11");
    public static final o aH = new o("F12");
    public static final o aI = new o("F13");
    public static final o aJ = new o("F14");
    public static final o aK = new o("F15");
    public static final o aL = new o("Kana");
    public static final o aM = new o("Convert");
    public static final o aN = new o("Noconvert");
    public static final o aO = new o("Yen");
    public static final o aP = new o("Num =");
    public static final o aQ = new o("Circumflex");
    public static final o aR = new o("At");
    public static final o aS = new o("Colon");
    public static final o aT = new o("Underline");
    public static final o aU = new o("Kanji");
    public static final o aV = new o("Stop");
    public static final o aW = new o("Ax");
    public static final o aX = new o("Unlabeled");
    public static final o aY = new o("Num Enter");
    public static final o aZ = new o("Right Control");
    public static final o ba = new o("Num ,");
    public static final o bb = new o("Num /");
    public static final o bc = new o("SysRq");
    public static final o bd = new o("Right Alt");
    public static final o be = new o("Pause");
    public static final o bf = new o("Home");
    public static final o bg = new o("Up");
    public static final o bh = new o("Pg Up");
    public static final o bi = new o("Left");
    public static final o bj = new o("Right");
    public static final o bk = new o("End");
    public static final o bl = new o("Down");
    public static final o bm = new o("Pg Down");
    public static final o bn = new o("Insert");
    public static final o bo = new o("Delete");
    public static final o bp = new o("Left Windows");
    public static final o bq = new o("Right Windows");
    public static final o br = new o("Apps");
    public static final o bs = new o("Power");
    public static final o bt = new o("Sleep");
    public static final o bu = new o("Unknown");

    protected o(String string) {
        super(string);
    }
}

