/*
 * Decompiled with CFR 0.150.
 */
package net.minecraft.q.g;

import net.minecraft.q.g.h;

public class a {
    public final float a;
    public final float b;
    public final float c;
    public final float d;
    public final float e;
    public final float f;
    public final float g;
    public final float h;
    public final float i;
    public final float j;
    public final float k;
    public final float l;
    public final float m;
    public final float n;
    public final float o;
    public final float p;
    public final int q;
    public final boolean r;
    public final boolean s;
    public final int t;
    public final boolean u;
    public final boolean v;
    public final boolean w;
    public final boolean x;
    public final boolean y;
    public final boolean z;
    public final boolean A;
    public final int B;
    public final boolean C;
    public final int D;
    public final boolean E;
    public final int F;
    public final int G;
    public final int H;
    public final int I;
    public final int J;
    public final int K;
    public final int L;
    public final int M;
    public final int N;
    public final int O;
    public final int P;
    public final int Q;
    public final int R;
    public final int S;
    public final int T;
    public final int U;
    public final int V;
    public final int W;
    public final int X;
    public final int Y;
    public final int Z;
    public final int aa;
    public final int ab;
    public final int ac;
    public final int ad;
    public final int ae;
    public final int af;
    public final int ag;
    public final int ah;
    public final int ai;
    public final int aj;
    public final int ak;
    public final int al;
    public final int am;
    public final int an;
    public final int ao;
    public final int ap;
    public final int aq;
    public final int ar;
    public final int as;
    public final int at;
    public final int au;
    public final int av;
    public final int aw;
    public final int ax;
    public final int ay;
    public final int az;

    private a(h h2) {
        this.a = h2.b;
        this.b = h2.c;
        this.c = h2.d;
        this.d = h2.e;
        this.e = h2.f;
        this.f = h2.g;
        this.g = h2.h;
        this.h = h2.i;
        this.i = h2.j;
        this.j = h2.k;
        this.k = h2.l;
        this.l = h2.m;
        this.m = h2.n;
        this.n = h2.o;
        this.o = h2.p;
        this.p = h2.q;
        this.q = h2.r;
        this.r = h2.s;
        this.s = h2.t;
        this.t = h2.u;
        this.u = h2.v;
        this.v = h2.w;
        this.w = h2.x;
        this.x = h2.y;
        this.y = h2.z;
        this.z = h2.A;
        this.A = h2.B;
        this.B = h2.C;
        this.C = h2.D;
        this.D = h2.E;
        this.E = h2.F;
        this.F = h2.G;
        this.G = h2.H;
        this.H = h2.I;
        this.I = h2.J;
        this.J = h2.K;
        this.K = h2.L;
        this.L = h2.M;
        this.M = h2.N;
        this.N = h2.O;
        this.O = h2.P;
        this.P = h2.Q;
        this.Q = h2.R;
        this.R = h2.S;
        this.S = h2.T;
        this.T = h2.U;
        this.U = h2.V;
        this.V = h2.W;
        this.W = h2.X;
        this.X = h2.Y;
        this.Y = h2.Z;
        this.Z = h2.aa;
        this.aa = h2.ab;
        this.ab = h2.ac;
        this.ac = h2.ad;
        this.ad = h2.ae;
        this.ae = h2.af;
        this.af = h2.ag;
        this.ag = h2.ah;
        this.ah = h2.ai;
        this.ai = h2.aj;
        this.aj = h2.ak;
        this.ak = h2.al;
        this.al = h2.am;
        this.am = h2.an;
        this.an = h2.ao;
        this.ao = h2.ap;
        this.ap = h2.aq;
        this.aq = h2.ar;
        this.ar = h2.as;
        this.as = h2.at;
        this.at = h2.au;
        this.au = h2.av;
        this.av = h2.aw;
        this.aw = h2.ax;
        this.ax = h2.ay;
        this.ay = h2.az;
        this.az = h2.aA;
    }

    /* synthetic */ a(h h2, a a2) {
        this(h2);
    }
}

