/*
 * Decompiled with CFR 0.150.
 */
package net.minecraft.a;

import net.minecraft.a.z;
import net.minecraft.u.bp;
import net.minecraft.u.bv;

/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public class f {
    public static final bv a;
    public static final bv b;
    public static final bv c;
    public static final bv d;
    public static final bv e;
    public static final bv f;
    public static final bv g;
    public static final bv h;
    public static final bv i;
    public static final bv j;
    public static final bv k;
    public static final bv l;
    public static final bv m;
    public static final bv n;
    public static final bv o;
    public static final bv p;
    public static final bv q;
    public static final bv r;
    public static final bv s;
    public static final bv t;
    public static final bv u;
    public static final bv v;
    public static final bv w;
    public static final bv x;
    public static final bv y;
    public static final bv z;
    public static final bv A;
    public static final bv B;
    public static final bv C;
    public static final bv D;
    public static final bv E;
    public static final bv F;
    public static final bv G;
    public static final bv H;
    public static final bv I;
    public static final bv J;
    public static final bv K;
    public static final bv L;
    public static final bv M;
    public static final bv N;
    public static final bv O;
    public static final bv P;
    public static final bv Q;
    public static final bv R;
    public static final bv S;
    public static final bv T;
    public static final bv U;
    public static final bv V;
    public static final bv W;
    public static final bv X;
    public static final bv Y;
    public static final bv Z;
    public static final bv aa;
    public static final bv ab;
    public static final bv ac;
    public static final bv ad;
    public static final bv ae;
    public static final bv af;
    public static final bv ag;
    public static final bv ah;
    public static final bv ai;
    public static final bv aj;
    public static final bv ak;
    public static final bv al;
    public static final bv am;
    public static final bv an;
    public static final bv ao;
    public static final bv ap;
    public static final bv aq;
    public static final bv ar;
    public static final bv as;
    public static final bv at;
    public static final bv au;
    public static final bv av;
    public static final bv aw;
    public static final bv ax;
    public static final bv ay;
    public static final bv az;
    public static final bv aA;
    public static final bv aB;
    public static final bv aC;
    public static final bv aD;
    public static final bv aE;
    public static final bv aF;
    public static final bv aG;
    public static final bv aH;
    public static final bv aI;
    public static final bv aJ;
    public static final bv aK;
    public static final bv aL;
    public static final bv aM;
    public static final bv aN;
    public static final bv aO;
    public static final bv aP;
    public static final bv aQ;
    public static final bv aR;
    public static final bv aS;
    public static final bv aT;
    public static final bv aU;
    public static final bv aV;
    public static final bv aW;
    public static final bv aX;
    public static final bv aY;
    public static final bv aZ;
    public static final bv ba;
    public static final bv bb;
    public static final bv bc;
    public static final bv bd;
    public static final bv be;
    public static final bv bf;
    public static final bv bg;
    public static final bv bh;
    public static final bv bi;
    public static final bv bj;
    public static final bv bk;
    public static final bv bl;
    public static final bv bm;
    public static final bv bn;
    public static final bv bo;
    public static final bv bp;
    public static final bv bq;
    public static final bv br;
    public static final bv bs;
    public static final bv bt;
    public static final bv bu;
    public static final bv bv;
    public static final bv bw;
    public static final bv bx;
    public static final bv by;
    public static final bv bz;
    public static final bv bA;
    public static final bv bB;
    public static final bv bC;
    public static final bv bD;
    public static final bv bE;
    public static final bv bF;
    public static final bv bG;
    public static final bv bH;
    public static final bv bI;
    public static final bv bJ;
    public static final bv bK;
    public static final bv bL;
    public static final bv bM;
    public static final bv bN;
    public static final bv bO;
    public static final bv bP;
    public static final bv bQ;
    public static final bv bR;
    public static final bv bS;
    public static final bv bT;
    public static final bv bU;
    public static final bv bV;
    public static final bv bW;
    public static final bv bX;
    public static final bv bY;
    public static final bv bZ;
    public static final bv ca;
    public static final bv cb;
    public static final bv cc;
    public static final bv cd;
    public static final bv ce;
    public static final bv cf;
    public static final bv cg;
    public static final bv ch;
    public static final bv ci;
    public static final bv cj;
    public static final bv ck;
    public static final bv cl;
    public static final bv cm;
    public static final bv cn;
    public static final bv co;
    public static final bv cp;
    public static final bv cq;
    public static final bv cr;
    public static final bv cs;
    public static final bv ct;
    public static final bv cu;
    public static final bv cv;
    public static final bv cw;
    public static final bv cx;
    public static final bv cy;
    public static final bv cz;
    public static final bv cA;
    public static final bv cB;
    public static final bv cC;
    public static final bv cD;
    public static final bv cE;
    public static final bv cF;
    public static final bv cG;
    public static final bv cH;
    public static final bv cI;
    public static final bv cJ;
    public static final bv cK;
    public static final bv cL;
    public static final bv cM;
    public static final bv cN;
    public static final bv cO;
    public static final bv cP;
    public static final bv cQ;
    public static final bv cR;
    public static final bv cS;
    public static final bv cT;
    public static final bv cU;
    public static final bv cV;
    public static final bv cW;
    public static final bv cX;
    public static final bv cY;
    public static final bv cZ;
    public static final bv da;
    public static final bv db;
    public static final bv dc;
    public static final bv dd;
    public static final bv de;
    public static final bv df;
    public static final bv dg;
    public static final bv dh;
    public static final bv di;
    public static final bv dj;
    public static final bv dk;
    public static final bv dl;
    public static final bv dm;
    public static final bv dn;
    public static final bv do;
    public static final bv dp;
    public static final bv dq;
    public static final bv dr;
    public static final bv ds;
    public static final bv dt;
    public static final bv du;
    public static final bv dv;
    public static final bv dw;
    public static final bv dx;
    public static final bv dy;
    public static final bv dz;
    public static final bv dA;
    public static final bv dB;
    public static final bv dC;
    public static final bv dD;
    public static final bv dE;
    public static final bv dF;
    public static final bv dG;
    public static final bv dH;
    public static final bv dI;
    public static final bv dJ;
    public static final bv dK;
    public static final bv dL;
    public static final bv dM;
    public static final bv dN;
    public static final bv dO;
    public static final bv dP;
    public static final bv dQ;
    public static final bv dR;
    public static final bv dS;
    public static final bv dT;
    public static final bv dU;
    public static final bv dV;
    public static final bv dW;
    public static final bv dX;
    public static final bv dY;
    public static final bv dZ;
    public static final bv ea;
    public static final bv eb;
    public static final bv ec;
    public static final bv ed;
    public static final bv ee;
    public static final bv ef;
    public static final bv eg;
    public static final bv eh;
    public static final bv ei;
    public static final bv ej;
    public static final bv ek;
    public static final bv el;
    public static final bv em;
    public static final bv en;
    public static final bv eo;
    public static final bv ep;
    public static final bv eq;
    public static final bv er;
    public static final bv es;
    public static final bv et;
    public static final bv eu;
    public static final bv ev;
    public static final bv ew;
    public static final bv ex;
    public static final bv ey;
    public static final bv ez;
    public static final bv eA;
    public static final bv eB;
    public static final bv eC;
    public static final bv eD;
    public static final bv eE;
    public static final bv eF;
    public static final bv eG;
    public static final bv eH;
    public static final bv eI;
    public static final bv eJ;
    public static final bv eK;
    public static final bv eL;
    public static final bv eM;
    public static final bv eN;
    public static final bv eO;
    public static final bv eP;
    public static final bv eQ;
    public static final bv eR;
    public static final bv eS;
    public static final bv eT;
    public static final bv eU;
    public static final bv eV;
    public static final bv eW;
    public static final bv eX;
    public static final bv eY;
    public static final bv eZ;
    public static final bv fa;
    public static final bv fb;
    public static final bv fc;
    public static final bv fd;
    public static final bv fe;
    public static final bv ff;
    public static final bv fg;
    public static final bv fh;
    public static final bv fi;
    public static final bv fj;
    public static final bv fk;
    public static final bv fl;
    public static final bv fm;
    public static final bv fn;
    public static final bv fo;
    public static final bv fp;
    public static final bv fq;
    public static final bv fr;
    public static final bv fs;
    public static final bv ft;
    public static final bv fu;
    public static final bv fv;
    public static final bv fw;
    public static final bv fx;
    public static final bv fy;
    public static final bv fz;
    public static final bv fA;
    public static final bv fB;
    public static final bv fC;
    public static final bv fD;
    public static final bv fE;
    public static final bv fF;
    public static final bv fG;
    public static final bv fH;
    public static final bv fI;
    public static final bv fJ;
    public static final bv fK;
    public static final bv fL;
    public static final bv fM;
    public static final bv fN;
    public static final bv fO;
    public static final bv fP;
    public static final bv fQ;
    public static final bv fR;
    public static final bv fS;
    public static final bv fT;
    public static final bv fU;
    public static final bv fV;
    public static final bv fW;
    public static final bv fX;
    public static final bv fY;
    public static final bv fZ;
    public static final bv ga;
    public static final bv gb;
    public static final bv gc;
    public static final bv gd;
    public static final bv ge;
    public static final bv gf;
    public static final bv gg;
    public static final bv gh;
    public static final bv gi;
    public static final bv gj;
    public static final bv gk;
    public static final bv gl;
    public static final bv gm;
    public static final bv gn;
    public static final bv go;
    public static final bv gp;
    public static final bv gq;
    public static final bv gr;
    public static final bv gs;
    public static final bv gt;
    public static final bv gu;
    public static final bv gv;
    public static final bv gw;
    public static final bv gx;
    public static final bv gy;
    public static final bv gz;
    public static final bv gA;
    public static final bv gB;
    public static final bv gC;
    public static final bv gD;
    public static final bv gE;
    public static final bv gF;
    public static final bv gG;
    public static final bv gH;
    public static final bv gI;
    public static final bv gJ;
    public static final bv gK;
    public static final bv gL;
    public static final bv gM;
    public static final bv gN;
    public static final bv gO;
    public static final bv gP;
    public static final bv gQ;
    public static final bv gR;
    public static final bv gS;
    public static final bv gT;
    public static final bv gU;
    public static final bv gV;
    public static final bv gW;
    public static final bv gX;
    public static final bv gY;
    public static final bv gZ;
    public static final bv ha;
    public static final bv hb;
    public static final bv hc;
    public static final bv hd;
    public static final bv he;
    public static final bv hf;
    public static final bv hg;
    public static final bv hh;
    public static final bv hi;
    public static final bv hj;
    public static final bv hk;
    public static final bv hl;
    public static final bv hm;
    public static final bv hn;
    public static final bv ho;
    public static final bv hp;
    public static final bv hq;
    public static final bv hr;
    public static final bv hs;
    public static final bv ht;
    public static final bv hu;
    public static final bv hv;
    public static final bv hw;
    public static final bv hx;
    public static final bv hy;
    public static final bv hz;
    public static final bv hA;
    public static final bv hB;
    public static final bv hC;
    public static final bv hD;
    public static final bv hE;
    public static final bv hF;
    public static final bv hG;
    public static final bv hH;
    public static final bv hI;
    public static final bv hJ;
    public static final bv hK;
    public static final bv hL;
    public static final bv hM;
    public static final bv hN;
    public static final bv hO;
    public static final bv hP;
    public static final bv hQ;
    public static final bv hR;
    public static final bv hS;
    public static final bv hT;
    public static final bv hU;

    static {
        if (!net.minecraft.a.z.a()) {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        }
        a = net.minecraft.a.f.a("ambient.cave.cave");
        b = net.minecraft.a.f.a("block.anvil.break");
        c = net.minecraft.a.f.a("block.anvil.destroy");
        d = net.minecraft.a.f.a("block.anvil.fall");
        e = net.minecraft.a.f.a("block.anvil.hit");
        f = net.minecraft.a.f.a("block.anvil.land");
        g = net.minecraft.a.f.a("block.anvil.place");
        h = net.minecraft.a.f.a("block.anvil.step");
        i = net.minecraft.a.f.a("block.anvil.use");
        j = net.minecraft.a.f.a("entity.armorstand.break");
        k = net.minecraft.a.f.a("entity.armorstand.fall");
        l = net.minecraft.a.f.a("entity.armorstand.hit");
        m = net.minecraft.a.f.a("entity.armorstand.place");
        n = net.minecraft.a.f.a("item.armor.equip_chain");
        o = net.minecraft.a.f.a("item.armor.equip_diamond");
        p = net.minecraft.a.f.a("item.armor.equip_generic");
        q = net.minecraft.a.f.a("item.armor.equip_gold");
        r = net.minecraft.a.f.a("item.armor.equip_iron");
        s = net.minecraft.a.f.a("item.armor.equip_leather");
        t = net.minecraft.a.f.a("entity.arrow.hit");
        u = net.minecraft.a.f.a("entity.arrow.hit_player");
        v = net.minecraft.a.f.a("entity.arrow.shoot");
        w = net.minecraft.a.f.a("entity.bat.ambient");
        x = net.minecraft.a.f.a("entity.bat.death");
        y = net.minecraft.a.f.a("entity.bat.hurt");
        z = net.minecraft.a.f.a("entity.bat.loop");
        A = net.minecraft.a.f.a("entity.bat.takeoff");
        B = net.minecraft.a.f.a("entity.blaze.ambient");
        C = net.minecraft.a.f.a("entity.blaze.burn");
        D = net.minecraft.a.f.a("entity.blaze.death");
        E = net.minecraft.a.f.a("entity.blaze.hurt");
        F = net.minecraft.a.f.a("entity.blaze.shoot");
        G = net.minecraft.a.f.a("entity.bobber.splash");
        H = net.minecraft.a.f.a("entity.bobber.throw");
        I = net.minecraft.a.f.a("item.bottle.fill");
        J = net.minecraft.a.f.a("item.bottle.fill_dragonbreath");
        K = net.minecraft.a.f.a("block.brewing_stand.brew");
        L = net.minecraft.a.f.a("item.bucket.empty");
        M = net.minecraft.a.f.a("item.bucket.empty_lava");
        N = net.minecraft.a.f.a("item.bucket.fill");
        O = net.minecraft.a.f.a("item.bucket.fill_lava");
        P = net.minecraft.a.f.a("entity.cat.ambient");
        Q = net.minecraft.a.f.a("entity.cat.death");
        R = net.minecraft.a.f.a("entity.cat.hiss");
        S = net.minecraft.a.f.a("entity.cat.hurt");
        T = net.minecraft.a.f.a("entity.cat.purr");
        U = net.minecraft.a.f.a("entity.cat.purreow");
        V = net.minecraft.a.f.a("block.chest.close");
        W = net.minecraft.a.f.a("block.chest.locked");
        X = net.minecraft.a.f.a("block.chest.open");
        Y = net.minecraft.a.f.a("entity.chicken.ambient");
        Z = net.minecraft.a.f.a("entity.chicken.death");
        aa = net.minecraft.a.f.a("entity.chicken.egg");
        ab = net.minecraft.a.f.a("entity.chicken.hurt");
        ac = net.minecraft.a.f.a("entity.chicken.step");
        ad = net.minecraft.a.f.a("block.chorus_flower.death");
        ae = net.minecraft.a.f.a("block.chorus_flower.grow");
        af = net.minecraft.a.f.a("item.chorus_fruit.teleport");
        ag = net.minecraft.a.f.a("block.cloth.break");
        ah = net.minecraft.a.f.a("block.cloth.fall");
        ai = net.minecraft.a.f.a("block.cloth.hit");
        aj = net.minecraft.a.f.a("block.cloth.place");
        ak = net.minecraft.a.f.a("block.cloth.step");
        al = net.minecraft.a.f.a("block.comparator.click");
        am = net.minecraft.a.f.a("entity.cow.ambient");
        an = net.minecraft.a.f.a("entity.cow.death");
        ao = net.minecraft.a.f.a("entity.cow.hurt");
        ap = net.minecraft.a.f.a("entity.cow.milk");
        aq = net.minecraft.a.f.a("entity.cow.step");
        ar = net.minecraft.a.f.a("entity.creeper.death");
        as = net.minecraft.a.f.a("entity.creeper.hurt");
        at = net.minecraft.a.f.a("entity.creeper.primed");
        au = net.minecraft.a.f.a("block.dispenser.dispense");
        av = net.minecraft.a.f.a("block.dispenser.fail");
        aw = net.minecraft.a.f.a("block.dispenser.launch");
        ax = net.minecraft.a.f.a("entity.donkey.ambient");
        ay = net.minecraft.a.f.a("entity.donkey.angry");
        az = net.minecraft.a.f.a("entity.donkey.chest");
        aA = net.minecraft.a.f.a("entity.donkey.death");
        aB = net.minecraft.a.f.a("entity.donkey.hurt");
        aC = net.minecraft.a.f.a("entity.egg.throw");
        aD = net.minecraft.a.f.a("entity.elder_guardian.ambient");
        aE = net.minecraft.a.f.a("entity.elder_guardian.ambient_land");
        aF = net.minecraft.a.f.a("entity.elder_guardian.curse");
        aG = net.minecraft.a.f.a("entity.elder_guardian.death");
        aH = net.minecraft.a.f.a("entity.elder_guardian.death_land");
        aI = net.minecraft.a.f.a("entity.elder_guardian.hurt");
        aJ = net.minecraft.a.f.a("entity.elder_guardian.hurt_land");
        aK = net.minecraft.a.f.a("item.elytra.flying");
        aL = net.minecraft.a.f.a("block.enchantment_table.use");
        aM = net.minecraft.a.f.a("block.enderchest.close");
        aN = net.minecraft.a.f.a("block.enderchest.open");
        aO = net.minecraft.a.f.a("entity.enderdragon.ambient");
        aP = net.minecraft.a.f.a("entity.enderdragon.death");
        aQ = net.minecraft.a.f.a("entity.enderdragon_fireball.explode");
        aR = net.minecraft.a.f.a("entity.enderdragon.flap");
        aS = net.minecraft.a.f.a("entity.enderdragon.growl");
        aT = net.minecraft.a.f.a("entity.enderdragon.hurt");
        aU = net.minecraft.a.f.a("entity.enderdragon.shoot");
        aV = net.minecraft.a.f.a("entity.endereye.launch");
        aW = net.minecraft.a.f.a("entity.endermen.ambient");
        aX = net.minecraft.a.f.a("entity.endermen.death");
        aY = net.minecraft.a.f.a("entity.endermen.hurt");
        aZ = net.minecraft.a.f.a("entity.endermen.scream");
        ba = net.minecraft.a.f.a("entity.endermen.stare");
        bb = net.minecraft.a.f.a("entity.endermen.teleport");
        bc = net.minecraft.a.f.a("entity.endermite.ambient");
        bd = net.minecraft.a.f.a("entity.endermite.death");
        be = net.minecraft.a.f.a("entity.endermite.hurt");
        bf = net.minecraft.a.f.a("entity.endermite.step");
        bg = net.minecraft.a.f.a("entity.enderpearl.throw");
        bh = net.minecraft.a.f.a("block.end_gateway.spawn");
        bi = net.minecraft.a.f.a("entity.experience_bottle.throw");
        bj = net.minecraft.a.f.a("entity.experience_orb.pickup");
        bk = net.minecraft.a.f.a("entity.experience_orb.touch");
        bl = net.minecraft.a.f.a("block.fence_gate.close");
        bm = net.minecraft.a.f.a("block.fence_gate.open");
        bn = net.minecraft.a.f.a("item.firecharge.use");
        bo = net.minecraft.a.f.a("entity.firework.blast");
        bp = net.minecraft.a.f.a("entity.firework.blast_far");
        bq = net.minecraft.a.f.a("entity.firework.large_blast");
        br = net.minecraft.a.f.a("entity.firework.large_blast_far");
        bs = net.minecraft.a.f.a("entity.firework.launch");
        bt = net.minecraft.a.f.a("entity.firework.shoot");
        bu = net.minecraft.a.f.a("entity.firework.twinkle");
        bv = net.minecraft.a.f.a("entity.firework.twinkle_far");
        bw = net.minecraft.a.f.a("block.fire.ambient");
        bx = net.minecraft.a.f.a("block.fire.extinguish");
        by = net.minecraft.a.f.a("item.flintandsteel.use");
        bz = net.minecraft.a.f.a("block.furnace.fire_crackle");
        bA = net.minecraft.a.f.a("entity.generic.big_fall");
        bB = net.minecraft.a.f.a("entity.generic.burn");
        bC = net.minecraft.a.f.a("entity.generic.death");
        bD = net.minecraft.a.f.a("entity.generic.drink");
        bE = net.minecraft.a.f.a("entity.generic.eat");
        bF = net.minecraft.a.f.a("entity.generic.explode");
        bG = net.minecraft.a.f.a("entity.generic.extinguish_fire");
        bH = net.minecraft.a.f.a("entity.generic.hurt");
        bI = net.minecraft.a.f.a("entity.generic.small_fall");
        bJ = net.minecraft.a.f.a("entity.generic.splash");
        bK = net.minecraft.a.f.a("entity.generic.swim");
        bL = net.minecraft.a.f.a("entity.ghast.ambient");
        bM = net.minecraft.a.f.a("entity.ghast.death");
        bN = net.minecraft.a.f.a("entity.ghast.hurt");
        bO = net.minecraft.a.f.a("entity.ghast.scream");
        bP = net.minecraft.a.f.a("entity.ghast.shoot");
        bQ = net.minecraft.a.f.a("entity.ghast.warn");
        bR = net.minecraft.a.f.a("block.glass.break");
        bS = net.minecraft.a.f.a("block.glass.fall");
        bT = net.minecraft.a.f.a("block.glass.hit");
        bU = net.minecraft.a.f.a("block.glass.place");
        bV = net.minecraft.a.f.a("block.glass.step");
        bW = net.minecraft.a.f.a("block.grass.break");
        bX = net.minecraft.a.f.a("block.grass.fall");
        bY = net.minecraft.a.f.a("block.grass.hit");
        bZ = net.minecraft.a.f.a("block.grass.place");
        ca = net.minecraft.a.f.a("block.grass.step");
        cb = net.minecraft.a.f.a("block.gravel.break");
        cc = net.minecraft.a.f.a("block.gravel.fall");
        cd = net.minecraft.a.f.a("block.gravel.hit");
        ce = net.minecraft.a.f.a("block.gravel.place");
        cf = net.minecraft.a.f.a("block.gravel.step");
        cg = net.minecraft.a.f.a("entity.guardian.ambient");
        ch = net.minecraft.a.f.a("entity.guardian.ambient_land");
        ci = net.minecraft.a.f.a("entity.guardian.attack");
        cj = net.minecraft.a.f.a("entity.guardian.death");
        ck = net.minecraft.a.f.a("entity.guardian.death_land");
        cl = net.minecraft.a.f.a("entity.guardian.flop");
        cm = net.minecraft.a.f.a("entity.guardian.hurt");
        cn = net.minecraft.a.f.a("entity.guardian.hurt_land");
        co = net.minecraft.a.f.a("item.hoe.till");
        cp = net.minecraft.a.f.a("entity.horse.ambient");
        cq = net.minecraft.a.f.a("entity.horse.angry");
        cr = net.minecraft.a.f.a("entity.horse.armor");
        cs = net.minecraft.a.f.a("entity.horse.breathe");
        ct = net.minecraft.a.f.a("entity.horse.death");
        cu = net.minecraft.a.f.a("entity.horse.eat");
        cv = net.minecraft.a.f.a("entity.horse.gallop");
        cw = net.minecraft.a.f.a("entity.horse.hurt");
        cx = net.minecraft.a.f.a("entity.horse.jump");
        cy = net.minecraft.a.f.a("entity.horse.land");
        cz = net.minecraft.a.f.a("entity.horse.saddle");
        cA = net.minecraft.a.f.a("entity.horse.step");
        cB = net.minecraft.a.f.a("entity.horse.step_wood");
        cC = net.minecraft.a.f.a("entity.hostile.big_fall");
        cD = net.minecraft.a.f.a("entity.hostile.death");
        cE = net.minecraft.a.f.a("entity.hostile.hurt");
        cF = net.minecraft.a.f.a("entity.hostile.small_fall");
        cG = net.minecraft.a.f.a("entity.hostile.splash");
        cH = net.minecraft.a.f.a("entity.hostile.swim");
        cI = net.minecraft.a.f.a("entity.husk.ambient");
        cJ = net.minecraft.a.f.a("entity.husk.death");
        cK = net.minecraft.a.f.a("entity.husk.hurt");
        cL = net.minecraft.a.f.a("entity.husk.step");
        cM = net.minecraft.a.f.a("entity.irongolem.attack");
        cN = net.minecraft.a.f.a("entity.irongolem.death");
        cO = net.minecraft.a.f.a("entity.irongolem.hurt");
        cP = net.minecraft.a.f.a("entity.irongolem.step");
        cQ = net.minecraft.a.f.a("block.iron_door.close");
        cR = net.minecraft.a.f.a("block.iron_door.open");
        cS = net.minecraft.a.f.a("block.iron_trapdoor.close");
        cT = net.minecraft.a.f.a("block.iron_trapdoor.open");
        cU = net.minecraft.a.f.a("entity.itemframe.add_item");
        cV = net.minecraft.a.f.a("entity.itemframe.break");
        cW = net.minecraft.a.f.a("entity.itemframe.place");
        cX = net.minecraft.a.f.a("entity.itemframe.remove_item");
        cY = net.minecraft.a.f.a("entity.itemframe.rotate_item");
        cZ = net.minecraft.a.f.a("entity.item.break");
        da = net.minecraft.a.f.a("entity.item.pickup");
        db = net.minecraft.a.f.a("block.ladder.break");
        dc = net.minecraft.a.f.a("block.ladder.fall");
        dd = net.minecraft.a.f.a("block.ladder.hit");
        de = net.minecraft.a.f.a("block.ladder.place");
        df = net.minecraft.a.f.a("block.ladder.step");
        dg = net.minecraft.a.f.a("block.lava.ambient");
        dh = net.minecraft.a.f.a("block.lava.extinguish");
        di = net.minecraft.a.f.a("block.lava.pop");
        dj = net.minecraft.a.f.a("entity.leashknot.break");
        dk = net.minecraft.a.f.a("entity.leashknot.place");
        dl = net.minecraft.a.f.a("block.lever.click");
        dm = net.minecraft.a.f.a("entity.lightning.impact");
        dn = net.minecraft.a.f.a("entity.lightning.thunder");
        do = net.minecraft.a.f.a("entity.lingeringpotion.throw");
        dp = net.minecraft.a.f.a("entity.magmacube.death");
        dq = net.minecraft.a.f.a("entity.magmacube.hurt");
        dr = net.minecraft.a.f.a("entity.magmacube.jump");
        ds = net.minecraft.a.f.a("entity.magmacube.squish");
        dt = net.minecraft.a.f.a("block.metal.break");
        du = net.minecraft.a.f.a("block.metal.fall");
        dv = net.minecraft.a.f.a("block.metal.hit");
        dw = net.minecraft.a.f.a("block.metal.place");
        dx = net.minecraft.a.f.a("block.metal_pressureplate.click_off");
        dy = net.minecraft.a.f.a("block.metal_pressureplate.click_on");
        dz = net.minecraft.a.f.a("block.metal.step");
        dA = net.minecraft.a.f.a("entity.minecart.inside");
        dB = net.minecraft.a.f.a("entity.minecart.riding");
        dC = net.minecraft.a.f.a("entity.mooshroom.shear");
        dD = net.minecraft.a.f.a("entity.mule.ambient");
        dE = net.minecraft.a.f.a("entity.mule.death");
        dF = net.minecraft.a.f.a("entity.mule.hurt");
        dG = net.minecraft.a.f.a("music.creative");
        dH = net.minecraft.a.f.a("music.credits");
        dI = net.minecraft.a.f.a("music.dragon");
        dJ = net.minecraft.a.f.a("music.end");
        dK = net.minecraft.a.f.a("music.game");
        dL = net.minecraft.a.f.a("music.menu");
        dM = net.minecraft.a.f.a("music.nether");
        dN = net.minecraft.a.f.a("block.note.basedrum");
        dO = net.minecraft.a.f.a("block.note.bass");
        dP = net.minecraft.a.f.a("block.note.harp");
        dQ = net.minecraft.a.f.a("block.note.hat");
        dR = net.minecraft.a.f.a("block.note.pling");
        dS = net.minecraft.a.f.a("block.note.snare");
        dT = net.minecraft.a.f.a("entity.painting.break");
        dU = net.minecraft.a.f.a("entity.painting.place");
        dV = net.minecraft.a.f.a("entity.pig.ambient");
        dW = net.minecraft.a.f.a("entity.pig.death");
        dX = net.minecraft.a.f.a("entity.pig.hurt");
        dY = net.minecraft.a.f.a("entity.pig.saddle");
        dZ = net.minecraft.a.f.a("entity.pig.step");
        ea = net.minecraft.a.f.a("block.piston.contract");
        eb = net.minecraft.a.f.a("block.piston.extend");
        ec = net.minecraft.a.f.a("entity.player.attack.crit");
        ed = net.minecraft.a.f.a("entity.player.attack.knockback");
        ee = net.minecraft.a.f.a("entity.player.attack.nodamage");
        ef = net.minecraft.a.f.a("entity.player.attack.strong");
        eg = net.minecraft.a.f.a("entity.player.attack.sweep");
        eh = net.minecraft.a.f.a("entity.player.attack.weak");
        ei = net.minecraft.a.f.a("entity.player.big_fall");
        ej = net.minecraft.a.f.a("entity.player.breath");
        ek = net.minecraft.a.f.a("entity.player.burp");
        el = net.minecraft.a.f.a("entity.player.death");
        em = net.minecraft.a.f.a("entity.player.hurt");
        en = net.minecraft.a.f.a("entity.player.levelup");
        eo = net.minecraft.a.f.a("entity.player.small_fall");
        ep = net.minecraft.a.f.a("entity.player.splash");
        eq = net.minecraft.a.f.a("entity.player.swim");
        er = net.minecraft.a.f.a("entity.polar_bear.ambient");
        es = net.minecraft.a.f.a("entity.polar_bear.baby_ambient");
        et = net.minecraft.a.f.a("entity.polar_bear.death");
        eu = net.minecraft.a.f.a("entity.polar_bear.hurt");
        ev = net.minecraft.a.f.a("entity.polar_bear.step");
        ew = net.minecraft.a.f.a("entity.polar_bear.warning");
        ex = net.minecraft.a.f.a("block.portal.ambient");
        ey = net.minecraft.a.f.a("block.portal.travel");
        ez = net.minecraft.a.f.a("block.portal.trigger");
        eA = net.minecraft.a.f.a("entity.rabbit.ambient");
        eB = net.minecraft.a.f.a("entity.rabbit.attack");
        eC = net.minecraft.a.f.a("entity.rabbit.death");
        eD = net.minecraft.a.f.a("entity.rabbit.hurt");
        eE = net.minecraft.a.f.a("entity.rabbit.jump");
        eF = net.minecraft.a.f.a("record.11");
        eG = net.minecraft.a.f.a("record.13");
        eH = net.minecraft.a.f.a("record.blocks");
        eI = net.minecraft.a.f.a("record.cat");
        eJ = net.minecraft.a.f.a("record.chirp");
        eK = net.minecraft.a.f.a("record.far");
        eL = net.minecraft.a.f.a("record.mall");
        eM = net.minecraft.a.f.a("record.mellohi");
        eN = net.minecraft.a.f.a("record.stal");
        eO = net.minecraft.a.f.a("record.strad");
        eP = net.minecraft.a.f.a("record.wait");
        eQ = net.minecraft.a.f.a("record.ward");
        eR = net.minecraft.a.f.a("block.redstone_torch.burnout");
        eS = net.minecraft.a.f.a("block.sand.break");
        eT = net.minecraft.a.f.a("block.sand.fall");
        eU = net.minecraft.a.f.a("block.sand.hit");
        eV = net.minecraft.a.f.a("block.sand.place");
        eW = net.minecraft.a.f.a("block.sand.step");
        eX = net.minecraft.a.f.a("entity.sheep.ambient");
        eY = net.minecraft.a.f.a("entity.sheep.death");
        eZ = net.minecraft.a.f.a("entity.sheep.hurt");
        fa = net.minecraft.a.f.a("entity.sheep.shear");
        fb = net.minecraft.a.f.a("entity.sheep.step");
        fc = net.minecraft.a.f.a("item.shield.block");
        fd = net.minecraft.a.f.a("item.shield.break");
        fe = net.minecraft.a.f.a("item.shovel.flatten");
        ff = net.minecraft.a.f.a("entity.shulker.ambient");
        fg = net.minecraft.a.f.a("entity.shulker_bullet.hit");
        fh = net.minecraft.a.f.a("entity.shulker_bullet.hurt");
        fi = net.minecraft.a.f.a("entity.shulker.close");
        fj = net.minecraft.a.f.a("entity.shulker.death");
        fk = net.minecraft.a.f.a("entity.shulker.hurt");
        fl = net.minecraft.a.f.a("entity.shulker.hurt_closed");
        fm = net.minecraft.a.f.a("entity.shulker.open");
        fn = net.minecraft.a.f.a("entity.shulker.shoot");
        fo = net.minecraft.a.f.a("entity.shulker.teleport");
        fp = net.minecraft.a.f.a("entity.silverfish.ambient");
        fq = net.minecraft.a.f.a("entity.silverfish.death");
        fr = net.minecraft.a.f.a("entity.silverfish.hurt");
        fs = net.minecraft.a.f.a("entity.silverfish.step");
        ft = net.minecraft.a.f.a("entity.skeleton.ambient");
        fu = net.minecraft.a.f.a("entity.skeleton.death");
        fv = net.minecraft.a.f.a("entity.skeleton_horse.ambient");
        fw = net.minecraft.a.f.a("entity.skeleton_horse.death");
        fx = net.minecraft.a.f.a("entity.skeleton_horse.hurt");
        fy = net.minecraft.a.f.a("entity.skeleton.hurt");
        fz = net.minecraft.a.f.a("entity.skeleton.shoot");
        fA = net.minecraft.a.f.a("entity.skeleton.step");
        fB = net.minecraft.a.f.a("entity.slime.attack");
        fC = net.minecraft.a.f.a("block.slime.break");
        fD = net.minecraft.a.f.a("entity.slime.death");
        fE = net.minecraft.a.f.a("block.slime.fall");
        fF = net.minecraft.a.f.a("block.slime.hit");
        fG = net.minecraft.a.f.a("entity.slime.hurt");
        fH = net.minecraft.a.f.a("entity.slime.jump");
        fI = net.minecraft.a.f.a("block.slime.place");
        fJ = net.minecraft.a.f.a("entity.slime.squish");
        fK = net.minecraft.a.f.a("block.slime.step");
        fL = net.minecraft.a.f.a("entity.small_magmacube.death");
        fM = net.minecraft.a.f.a("entity.small_magmacube.hurt");
        fN = net.minecraft.a.f.a("entity.small_magmacube.squish");
        fO = net.minecraft.a.f.a("entity.small_slime.death");
        fP = net.minecraft.a.f.a("entity.small_slime.hurt");
        fQ = net.minecraft.a.f.a("entity.small_slime.jump");
        fR = net.minecraft.a.f.a("entity.small_slime.squish");
        fS = net.minecraft.a.f.a("entity.snowball.throw");
        fT = net.minecraft.a.f.a("entity.snowman.ambient");
        fU = net.minecraft.a.f.a("entity.snowman.death");
        fV = net.minecraft.a.f.a("entity.snowman.hurt");
        fW = net.minecraft.a.f.a("entity.snowman.shoot");
        fX = net.minecraft.a.f.a("block.snow.break");
        fY = net.minecraft.a.f.a("block.snow.fall");
        fZ = net.minecraft.a.f.a("block.snow.hit");
        ga = net.minecraft.a.f.a("block.snow.place");
        gb = net.minecraft.a.f.a("block.snow.step");
        gc = net.minecraft.a.f.a("entity.spider.ambient");
        gd = net.minecraft.a.f.a("entity.spider.death");
        ge = net.minecraft.a.f.a("entity.spider.hurt");
        gf = net.minecraft.a.f.a("entity.spider.step");
        gg = net.minecraft.a.f.a("entity.splash_potion.break");
        gh = net.minecraft.a.f.a("entity.splash_potion.throw");
        gi = net.minecraft.a.f.a("entity.squid.ambient");
        gj = net.minecraft.a.f.a("entity.squid.death");
        gk = net.minecraft.a.f.a("entity.squid.hurt");
        gl = net.minecraft.a.f.a("block.stone.break");
        gm = net.minecraft.a.f.a("block.stone_button.click_off");
        gn = net.minecraft.a.f.a("block.stone_button.click_on");
        go = net.minecraft.a.f.a("block.stone.fall");
        gp = net.minecraft.a.f.a("block.stone.hit");
        gq = net.minecraft.a.f.a("block.stone.place");
        gr = net.minecraft.a.f.a("block.stone_pressureplate.click_off");
        gs = net.minecraft.a.f.a("block.stone_pressureplate.click_on");
        gt = net.minecraft.a.f.a("block.stone.step");
        gu = net.minecraft.a.f.a("entity.stray.ambient");
        gv = net.minecraft.a.f.a("entity.stray.death");
        gw = net.minecraft.a.f.a("entity.stray.hurt");
        gx = net.minecraft.a.f.a("entity.stray.step");
        gy = net.minecraft.a.f.a("enchant.thorns.hit");
        gz = net.minecraft.a.f.a("entity.tnt.primed");
        gA = net.minecraft.a.f.a("block.tripwire.attach");
        gB = net.minecraft.a.f.a("block.tripwire.click_off");
        gC = net.minecraft.a.f.a("block.tripwire.click_on");
        gD = net.minecraft.a.f.a("block.tripwire.detach");
        gE = net.minecraft.a.f.a("ui.button.click");
        gF = net.minecraft.a.f.a("entity.villager.ambient");
        gG = net.minecraft.a.f.a("entity.villager.death");
        gH = net.minecraft.a.f.a("entity.villager.hurt");
        gI = net.minecraft.a.f.a("entity.villager.no");
        gJ = net.minecraft.a.f.a("entity.villager.trading");
        gK = net.minecraft.a.f.a("entity.villager.yes");
        gL = net.minecraft.a.f.a("block.waterlily.place");
        gM = net.minecraft.a.f.a("block.water.ambient");
        gN = net.minecraft.a.f.a("weather.rain");
        gO = net.minecraft.a.f.a("weather.rain.above");
        gP = net.minecraft.a.f.a("entity.witch.ambient");
        gQ = net.minecraft.a.f.a("entity.witch.death");
        gR = net.minecraft.a.f.a("entity.witch.drink");
        gS = net.minecraft.a.f.a("entity.witch.hurt");
        gT = net.minecraft.a.f.a("entity.witch.throw");
        gU = net.minecraft.a.f.a("entity.wither.ambient");
        gV = net.minecraft.a.f.a("entity.wither.break_block");
        gW = net.minecraft.a.f.a("entity.wither.death");
        gX = net.minecraft.a.f.a("entity.wither.hurt");
        gY = net.minecraft.a.f.a("entity.wither.shoot");
        gZ = net.minecraft.a.f.a("entity.wither.spawn");
        ha = net.minecraft.a.f.a("entity.wither_skeleton.ambient");
        hb = net.minecraft.a.f.a("entity.wither_skeleton.death");
        hc = net.minecraft.a.f.a("entity.wither_skeleton.hurt");
        hd = net.minecraft.a.f.a("entity.wither_skeleton.step");
        he = net.minecraft.a.f.a("entity.wolf.ambient");
        hf = net.minecraft.a.f.a("entity.wolf.death");
        hg = net.minecraft.a.f.a("entity.wolf.growl");
        hh = net.minecraft.a.f.a("entity.wolf.howl");
        hi = net.minecraft.a.f.a("entity.wolf.hurt");
        hj = net.minecraft.a.f.a("entity.wolf.pant");
        hk = net.minecraft.a.f.a("entity.wolf.shake");
        hl = net.minecraft.a.f.a("entity.wolf.step");
        hm = net.minecraft.a.f.a("entity.wolf.whine");
        hn = net.minecraft.a.f.a("block.wooden_door.close");
        ho = net.minecraft.a.f.a("block.wooden_door.open");
        hp = net.minecraft.a.f.a("block.wooden_trapdoor.close");
        hq = net.minecraft.a.f.a("block.wooden_trapdoor.open");
        hr = net.minecraft.a.f.a("block.wood.break");
        hs = net.minecraft.a.f.a("block.wood_button.click_off");
        ht = net.minecraft.a.f.a("block.wood_button.click_on");
        hu = net.minecraft.a.f.a("block.wood.fall");
        hv = net.minecraft.a.f.a("block.wood.hit");
        hw = net.minecraft.a.f.a("block.wood.place");
        hx = net.minecraft.a.f.a("block.wood_pressureplate.click_off");
        hy = net.minecraft.a.f.a("block.wood_pressureplate.click_on");
        hz = net.minecraft.a.f.a("block.wood.step");
        hA = net.minecraft.a.f.a("entity.zombie.ambient");
        hB = net.minecraft.a.f.a("entity.zombie.attack_door_wood");
        hC = net.minecraft.a.f.a("entity.zombie.attack_iron_door");
        hD = net.minecraft.a.f.a("entity.zombie.break_door_wood");
        hE = net.minecraft.a.f.a("entity.zombie.death");
        hF = net.minecraft.a.f.a("entity.zombie_horse.ambient");
        hG = net.minecraft.a.f.a("entity.zombie_horse.death");
        hH = net.minecraft.a.f.a("entity.zombie_horse.hurt");
        hI = net.minecraft.a.f.a("entity.zombie.hurt");
        hJ = net.minecraft.a.f.a("entity.zombie.infect");
        hK = net.minecraft.a.f.a("entity.zombie_pig.ambient");
        hL = net.minecraft.a.f.a("entity.zombie_pig.angry");
        hM = net.minecraft.a.f.a("entity.zombie_pig.death");
        hN = net.minecraft.a.f.a("entity.zombie_pig.hurt");
        hO = net.minecraft.a.f.a("entity.zombie.step");
        hP = net.minecraft.a.f.a("entity.zombie_villager.ambient");
        hQ = net.minecraft.a.f.a("entity.zombie_villager.converted");
        hR = net.minecraft.a.f.a("entity.zombie_villager.cure");
        hS = net.minecraft.a.f.a("entity.zombie_villager.death");
        hT = net.minecraft.a.f.a("entity.zombie_villager.hurt");
        hU = net.minecraft.a.f.a("entity.zombie_villager.step");
    }

    private static bv a(String string) {
        bv bv2 = (bv)net.minecraft.u.bv.a.a(new bp(string));
        if (bv2 == null) {
            throw new IllegalStateException("Invalid Sound requested: " + string);
        }
        return bv2;
    }
}

