/*
 * Decompiled with CFR 0.150.
 */
package net.minecraft.a;

import com.a.a.d.aad;
import java.util.Set;
import net.minecraft.a.z;
import net.minecraft.g.ba;
import net.minecraft.g.bb;
import net.minecraft.g.bh;
import net.minecraft.g.bl;
import net.minecraft.g.bm;
import net.minecraft.g.cm;
import net.minecraft.g.cn;
import net.minecraft.g.co;
import net.minecraft.g.cw;
import net.minecraft.g.ds;
import net.minecraft.g.dy;
import net.minecraft.g.ea;
import net.minecraft.g.ed;
import net.minecraft.g.er;
import net.minecraft.g.fc;
import net.minecraft.g.ft;
import net.minecraft.g.ga;
import net.minecraft.g.gb;
import net.minecraft.g.gc;
import net.minecraft.g.gd;
import net.minecraft.g.ge;
import net.minecraft.g.hf;
import net.minecraft.g.hi;
import net.minecraft.g.hk;
import net.minecraft.g.hn;
import net.minecraft.g.ho;
import net.minecraft.g.hp;
import net.minecraft.g.hs;
import net.minecraft.g.hw;
import net.minecraft.g.ib;
import net.minecraft.g.id;
import net.minecraft.g.l;
import net.minecraft.g.u;
import net.minecraft.u.bp;

public class p {
    private static final Set dl;
    public static final cn a;
    public static final cn b;
    public static final hk c;
    public static final cn d;
    public static final cn e;
    public static final cn f;
    public static final cn g;
    public static final cn h;
    public static final gc i;
    public static final dy j;
    public static final gc k;
    public static final dy l;
    public static final gd m;
    public static final cn n;
    public static final cn o;
    public static final cn p;
    public static final cn q;
    public static final cn r;
    public static final cn s;
    public static final bm t;
    public static final bm u;
    public static final cn v;
    public static final cn w;
    public static final cn x;
    public static final cn y;
    public static final cn z;
    public static final cn A;
    public static final cn B;
    public static final cn C;
    public static final cn D;
    public static final cn E;
    public static final id F;
    public static final cn G;
    public static final hi H;
    public static final ea I;
    public static final id J;
    public static final co K;
    public static final cn L;
    public static final ds M;
    public static final gb N;
    public static final gb O;
    public static final ft P;
    public static final ft Q;
    public static final cn R;
    public static final cn S;
    public static final bl T;
    public static final bl U;
    public static final cn V;
    public static final cn W;
    public static final cn X;
    public static final cn Y;
    public static final cn Z;
    public static final cn aa;
    public static final hp ab;
    public static final cn ac;
    public static final cn ad;
    public static final ib ae;
    public static final ed af;
    public static final cn ag;
    public static final cn ah;
    public static final cn ai;
    public static final cn aj;
    public static final cn ak;
    public static final cn al;
    public static final cn am;
    public static final cn an;
    public static final ga ao;
    public static final ga ap;
    public static final ga aq;
    public static final ga ar;
    public static final ga as;
    public static final ga at;
    public static final cn au;
    public static final cn av;
    public static final cn aw;
    public static final cn ax;
    public static final cn ay;
    public static final cn az;
    public static final ga aA;
    public static final cn aB;
    public static final cn aC;
    public static final cn aD;
    public static final cn aE;
    public static final cn aF;
    public static final cn aG;
    public static final cn aH;
    public static final cn aI;
    public static final cn aJ;
    public static final ho aK;
    public static final cn aL;
    public static final ge aM;
    public static final cn aN;
    public static final cn aO;
    public static final cn aP;
    public static final cn aQ;
    public static final cn aR;
    public static final cn aS;
    public static final cn aT;
    public static final cn aU;
    public static final cn aV;
    public static final cn aW;
    public static final cn aX;
    public static final hn aY;
    public static final cn aZ;
    public static final cn ba;
    public static final cm bb;
    public static final cm bc;
    public static final cn bd;
    public static final cn be;
    public static final cn bf;
    public static final cn bg;
    public static final cn bh;
    public static final cn bi;
    public static final cn bj;
    public static final cn bk;
    public static final cn bl;
    public static final cn bm;
    public static final cn bn;
    public static final cn bo;
    public static final cn bp;
    public static final cn bq;
    public static final cn br;
    public static final cn bs;
    public static final cn bt;
    public static final cn bu;
    public static final cn bv;
    public static final cw bw;
    public static final cn bx;
    public static final cn by;
    public static final cn bz;
    public static final cn bA;
    public static final cn bB;
    public static final cn bC;
    public static final cn bD;
    public static final ba bE;
    public static final cn bF;
    public static final cn bG;
    public static final cn bH;
    public static final cn bI;
    public static final cn bJ;
    public static final cn bK;
    public static final bl bL;
    public static final bl bM;
    public static final cn bN;
    public static final cn bO;
    public static final cn bP;
    public static final cn bQ;
    public static final u bR;
    public static final cn bS;
    public static final cn bT;
    public static final cn bU;
    public static final cn bV;
    public static final cn bW;
    public static final cn bX;
    public static final bb bY;
    public static final cn bZ;
    public static final cn ca;
    public static final cn cb;
    public static final cn cc;
    public static final cn cd;
    public static final hs ce;
    public static final cn cf;
    public static final cn cg;
    public static final cn ch;
    public static final cn ci;
    public static final er cj;
    public static final er ck;
    public static final fc cl;
    public static final fc cm;
    public static final cn cn;
    public static final cn co;
    public static final l cp;
    public static final cn cq;
    public static final cn cr;
    public static final cn cs;
    public static final cn ct;
    public static final cn cu;
    public static final cn cv;
    public static final cn cw;
    public static final cn cx;
    public static final cn cy;
    public static final cn cz;
    public static final cn cA;
    public static final cn cB;
    public static final cn cC;
    public static final cn cD;
    public static final cn cE;
    public static final bh cF;
    public static final hw cG;
    public static final hf cH;
    public static final cn cI;
    public static final cn cJ;
    public static final cn cK;
    public static final cn cL;
    public static final cn cM;
    public static final cn cN;
    public static final bl cO;
    public static final bl cP;
    public static final cn cQ;
    public static final cn cR;
    public static final cn cS;
    public static final cn cT;
    public static final cn cU;
    public static final cn cV;
    public static final bl cW;
    public static final bl cX;
    public static final cn cY;
    public static final cn cZ;
    public static final cn da;
    public static final cn db;
    public static final cn dc;
    public static final cn dd;
    public static final cn de;
    public static final cn df;
    public static final cn dg;
    public static final cn dh;
    public static final cn di;
    public static final cn dj;
    public static final cn dk;

    static {
        if (!net.minecraft.a.z.a()) {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }
        dl = aad.a();
        a = net.minecraft.a.p.a("air");
        b = net.minecraft.a.p.a("stone");
        c = (hk)net.minecraft.a.p.a("grass");
        d = net.minecraft.a.p.a("dirt");
        e = net.minecraft.a.p.a("cobblestone");
        f = net.minecraft.a.p.a("planks");
        g = net.minecraft.a.p.a("sapling");
        h = net.minecraft.a.p.a("bedrock");
        i = (gc)net.minecraft.a.p.a("flowing_water");
        j = (dy)net.minecraft.a.p.a("water");
        k = (gc)net.minecraft.a.p.a("flowing_lava");
        l = (dy)net.minecraft.a.p.a("lava");
        m = (gd)net.minecraft.a.p.a("sand");
        n = net.minecraft.a.p.a("gravel");
        o = net.minecraft.a.p.a("gold_ore");
        p = net.minecraft.a.p.a("iron_ore");
        q = net.minecraft.a.p.a("coal_ore");
        r = net.minecraft.a.p.a("log");
        s = net.minecraft.a.p.a("log2");
        t = (bm)net.minecraft.a.p.a("leaves");
        u = (bm)net.minecraft.a.p.a("leaves2");
        v = net.minecraft.a.p.a("sponge");
        w = net.minecraft.a.p.a("glass");
        x = net.minecraft.a.p.a("lapis_ore");
        y = net.minecraft.a.p.a("lapis_block");
        z = net.minecraft.a.p.a("dispenser");
        A = net.minecraft.a.p.a("sandstone");
        B = net.minecraft.a.p.a("noteblock");
        C = net.minecraft.a.p.a("bed");
        D = net.minecraft.a.p.a("golden_rail");
        E = net.minecraft.a.p.a("detector_rail");
        F = (id)net.minecraft.a.p.a("sticky_piston");
        G = net.minecraft.a.p.a("web");
        H = (hi)net.minecraft.a.p.a("tallgrass");
        I = (ea)net.minecraft.a.p.a("deadbush");
        J = (id)net.minecraft.a.p.a("piston");
        K = (co)net.minecraft.a.p.a("piston_head");
        L = net.minecraft.a.p.a("wool");
        M = (ds)net.minecraft.a.p.a("piston_extension");
        N = (gb)net.minecraft.a.p.a("yellow_flower");
        O = (gb)net.minecraft.a.p.a("red_flower");
        P = (ft)net.minecraft.a.p.a("brown_mushroom");
        Q = (ft)net.minecraft.a.p.a("red_mushroom");
        R = net.minecraft.a.p.a("gold_block");
        S = net.minecraft.a.p.a("iron_block");
        T = (bl)net.minecraft.a.p.a("double_stone_slab");
        U = (bl)net.minecraft.a.p.a("stone_slab");
        V = net.minecraft.a.p.a("brick_block");
        W = net.minecraft.a.p.a("tnt");
        X = net.minecraft.a.p.a("bookshelf");
        Y = net.minecraft.a.p.a("mossy_cobblestone");
        Z = net.minecraft.a.p.a("obsidian");
        aa = net.minecraft.a.p.a("torch");
        ab = (hp)net.minecraft.a.p.a("fire");
        ac = net.minecraft.a.p.a("mob_spawner");
        ad = net.minecraft.a.p.a("oak_stairs");
        ae = (ib)net.minecraft.a.p.a("chest");
        af = (ed)net.minecraft.a.p.a("redstone_wire");
        ag = net.minecraft.a.p.a("diamond_ore");
        ah = net.minecraft.a.p.a("diamond_block");
        ai = net.minecraft.a.p.a("crafting_table");
        aj = net.minecraft.a.p.a("wheat");
        ak = net.minecraft.a.p.a("farmland");
        al = net.minecraft.a.p.a("furnace");
        am = net.minecraft.a.p.a("lit_furnace");
        an = net.minecraft.a.p.a("standing_sign");
        ao = (ga)net.minecraft.a.p.a("wooden_door");
        ap = (ga)net.minecraft.a.p.a("spruce_door");
        aq = (ga)net.minecraft.a.p.a("birch_door");
        ar = (ga)net.minecraft.a.p.a("jungle_door");
        as = (ga)net.minecraft.a.p.a("acacia_door");
        at = (ga)net.minecraft.a.p.a("dark_oak_door");
        au = net.minecraft.a.p.a("ladder");
        av = net.minecraft.a.p.a("rail");
        aw = net.minecraft.a.p.a("stone_stairs");
        ax = net.minecraft.a.p.a("wall_sign");
        ay = net.minecraft.a.p.a("lever");
        az = net.minecraft.a.p.a("stone_pressure_plate");
        aA = (ga)net.minecraft.a.p.a("iron_door");
        aB = net.minecraft.a.p.a("wooden_pressure_plate");
        aC = net.minecraft.a.p.a("redstone_ore");
        aD = net.minecraft.a.p.a("lit_redstone_ore");
        aE = net.minecraft.a.p.a("unlit_redstone_torch");
        aF = net.minecraft.a.p.a("redstone_torch");
        aG = net.minecraft.a.p.a("stone_button");
        aH = net.minecraft.a.p.a("snow_layer");
        aI = net.minecraft.a.p.a("ice");
        aJ = net.minecraft.a.p.a("snow");
        aK = (ho)net.minecraft.a.p.a("cactus");
        aL = net.minecraft.a.p.a("clay");
        aM = (ge)net.minecraft.a.p.a("reeds");
        aN = net.minecraft.a.p.a("jukebox");
        aO = net.minecraft.a.p.a("fence");
        aP = net.minecraft.a.p.a("spruce_fence");
        aQ = net.minecraft.a.p.a("birch_fence");
        aR = net.minecraft.a.p.a("jungle_fence");
        aS = net.minecraft.a.p.a("dark_oak_fence");
        aT = net.minecraft.a.p.a("acacia_fence");
        aU = net.minecraft.a.p.a("pumpkin");
        aV = net.minecraft.a.p.a("netherrack");
        aW = net.minecraft.a.p.a("soul_sand");
        aX = net.minecraft.a.p.a("glowstone");
        aY = (hn)net.minecraft.a.p.a("portal");
        aZ = net.minecraft.a.p.a("lit_pumpkin");
        ba = net.minecraft.a.p.a("cake");
        bb = (cm)net.minecraft.a.p.a("unpowered_repeater");
        bc = (cm)net.minecraft.a.p.a("powered_repeater");
        bd = net.minecraft.a.p.a("trapdoor");
        be = net.minecraft.a.p.a("monster_egg");
        bf = net.minecraft.a.p.a("stonebrick");
        bg = net.minecraft.a.p.a("brown_mushroom_block");
        bh = net.minecraft.a.p.a("red_mushroom_block");
        bi = net.minecraft.a.p.a("iron_bars");
        bj = net.minecraft.a.p.a("glass_pane");
        bk = net.minecraft.a.p.a("melon_block");
        bl = net.minecraft.a.p.a("pumpkin_stem");
        bm = net.minecraft.a.p.a("melon_stem");
        bn = net.minecraft.a.p.a("vine");
        bo = net.minecraft.a.p.a("fence_gate");
        bp = net.minecraft.a.p.a("spruce_fence_gate");
        bq = net.minecraft.a.p.a("birch_fence_gate");
        br = net.minecraft.a.p.a("jungle_fence_gate");
        bs = net.minecraft.a.p.a("dark_oak_fence_gate");
        bt = net.minecraft.a.p.a("acacia_fence_gate");
        bu = net.minecraft.a.p.a("brick_stairs");
        bv = net.minecraft.a.p.a("stone_brick_stairs");
        bw = (cw)net.minecraft.a.p.a("mycelium");
        bx = net.minecraft.a.p.a("waterlily");
        by = net.minecraft.a.p.a("nether_brick");
        bz = net.minecraft.a.p.a("nether_brick_fence");
        bA = net.minecraft.a.p.a("nether_brick_stairs");
        bB = net.minecraft.a.p.a("nether_wart");
        bC = net.minecraft.a.p.a("enchanting_table");
        bD = net.minecraft.a.p.a("brewing_stand");
        bE = (ba)net.minecraft.a.p.a("cauldron");
        bF = net.minecraft.a.p.a("end_portal");
        bG = net.minecraft.a.p.a("end_portal_frame");
        bH = net.minecraft.a.p.a("end_stone");
        bI = net.minecraft.a.p.a("dragon_egg");
        bJ = net.minecraft.a.p.a("redstone_lamp");
        bK = net.minecraft.a.p.a("lit_redstone_lamp");
        bL = (bl)net.minecraft.a.p.a("double_wooden_slab");
        bM = (bl)net.minecraft.a.p.a("wooden_slab");
        bN = net.minecraft.a.p.a("cocoa");
        bO = net.minecraft.a.p.a("sandstone_stairs");
        bP = net.minecraft.a.p.a("emerald_ore");
        bQ = net.minecraft.a.p.a("ender_chest");
        bR = (u)net.minecraft.a.p.a("tripwire_hook");
        bS = net.minecraft.a.p.a("tripwire");
        bT = net.minecraft.a.p.a("emerald_block");
        bU = net.minecraft.a.p.a("spruce_stairs");
        bV = net.minecraft.a.p.a("birch_stairs");
        bW = net.minecraft.a.p.a("jungle_stairs");
        bX = net.minecraft.a.p.a("command_block");
        bY = (bb)net.minecraft.a.p.a("beacon");
        bZ = net.minecraft.a.p.a("cobblestone_wall");
        ca = net.minecraft.a.p.a("flower_pot");
        cb = net.minecraft.a.p.a("carrots");
        cc = net.minecraft.a.p.a("potatoes");
        cd = net.minecraft.a.p.a("wooden_button");
        ce = (hs)net.minecraft.a.p.a("skull");
        cf = net.minecraft.a.p.a("anvil");
        cg = net.minecraft.a.p.a("trapped_chest");
        ch = net.minecraft.a.p.a("light_weighted_pressure_plate");
        ci = net.minecraft.a.p.a("heavy_weighted_pressure_plate");
        cj = (er)net.minecraft.a.p.a("unpowered_comparator");
        ck = (er)net.minecraft.a.p.a("powered_comparator");
        cl = (fc)net.minecraft.a.p.a("daylight_detector");
        cm = (fc)net.minecraft.a.p.a("daylight_detector_inverted");
        cn = net.minecraft.a.p.a("redstone_block");
        co = net.minecraft.a.p.a("quartz_ore");
        cp = (l)net.minecraft.a.p.a("hopper");
        cq = net.minecraft.a.p.a("quartz_block");
        cr = net.minecraft.a.p.a("quartz_stairs");
        cs = net.minecraft.a.p.a("activator_rail");
        ct = net.minecraft.a.p.a("dropper");
        cu = net.minecraft.a.p.a("stained_hardened_clay");
        cv = net.minecraft.a.p.a("barrier");
        cw = net.minecraft.a.p.a("iron_trapdoor");
        cx = net.minecraft.a.p.a("hay_block");
        cy = net.minecraft.a.p.a("carpet");
        cz = net.minecraft.a.p.a("hardened_clay");
        cA = net.minecraft.a.p.a("coal_block");
        cB = net.minecraft.a.p.a("packed_ice");
        cC = net.minecraft.a.p.a("acacia_stairs");
        cD = net.minecraft.a.p.a("dark_oak_stairs");
        cE = net.minecraft.a.p.a("slime");
        cF = (bh)net.minecraft.a.p.a("double_plant");
        cG = (hw)net.minecraft.a.p.a("stained_glass");
        cH = (hf)net.minecraft.a.p.a("stained_glass_pane");
        cI = net.minecraft.a.p.a("prismarine");
        cJ = net.minecraft.a.p.a("sea_lantern");
        cK = net.minecraft.a.p.a("standing_banner");
        cL = net.minecraft.a.p.a("wall_banner");
        cM = net.minecraft.a.p.a("red_sandstone");
        cN = net.minecraft.a.p.a("red_sandstone_stairs");
        cO = (bl)net.minecraft.a.p.a("double_stone_slab2");
        cP = (bl)net.minecraft.a.p.a("stone_slab2");
        cQ = net.minecraft.a.p.a("end_rod");
        cR = net.minecraft.a.p.a("chorus_plant");
        cS = net.minecraft.a.p.a("chorus_flower");
        cT = net.minecraft.a.p.a("purpur_block");
        cU = net.minecraft.a.p.a("purpur_pillar");
        cV = net.minecraft.a.p.a("purpur_stairs");
        cW = (bl)net.minecraft.a.p.a("purpur_double_slab");
        cX = (bl)net.minecraft.a.p.a("purpur_slab");
        cY = net.minecraft.a.p.a("end_bricks");
        cZ = net.minecraft.a.p.a("beetroots");
        da = net.minecraft.a.p.a("grass_path");
        db = net.minecraft.a.p.a("end_gateway");
        dc = net.minecraft.a.p.a("repeating_command_block");
        dd = net.minecraft.a.p.a("chain_command_block");
        de = net.minecraft.a.p.a("frosted_ice");
        df = net.minecraft.a.p.a("magma");
        dg = net.minecraft.a.p.a("nether_wart_block");
        dh = net.minecraft.a.p.a("red_nether_brick");
        di = net.minecraft.a.p.a("bone_block");
        dj = net.minecraft.a.p.a("structure_void");
        dk = net.minecraft.a.p.a("structure_block");
        dl.clear();
    }

    private static cn a(String string) {
        cn cn2 = (cn)net.minecraft.g.cn.v.a(new bp(string));
        if (!dl.add(cn2)) {
            throw new IllegalStateException("Invalid Block requested: " + string);
        }
        return cn2;
    }
}

