/*
 * Decompiled with CFR 0.150.
 */
package net.minecraft.a;

import net.minecraft.a.z;
import net.minecraft.m.ae;
import net.minecraft.m.ak;
import net.minecraft.m.al;
import net.minecraft.m.aq;
import net.minecraft.m.bf;
import net.minecraft.m.bn;
import net.minecraft.m.cg;
import net.minecraft.m.cl;
import net.minecraft.m.dn;
import net.minecraft.m.f;
import net.minecraft.u.bp;

public class w {
    public static final cg a;
    public static final cg b;
    public static final cg c;
    public static final cg d;
    public static final cg e;
    public static final bn f;
    public static final cg g;
    public static final cg h;
    public static final cg i;
    public static final cg j;
    public static final cg k;
    public static final cg l;
    public static final cg m;
    public static final cg n;
    public static final cg o;
    public static final cg p;
    public static final cg q;
    public static final cg r;
    public static final cg s;
    public static final cg t;
    public static final cg u;
    public static final cg v;
    public static final cg w;
    public static final cg x;
    public static final cg y;
    public static final cg z;
    public static final cg A;
    public static final cg B;
    public static final cg C;
    public static final cg D;
    public static final cg E;
    public static final cg F;
    public static final cg G;
    public static final cg H;
    public static final cg I;
    public static final cg J;
    public static final cg K;
    public static final cg L;
    public static final cg M;
    public static final cg N;
    public static final cg O;
    public static final cg P;
    public static final cg Q;
    public static final cg R;
    public static final dn S;
    public static final dn T;
    public static final dn U;
    public static final dn V;
    public static final dn W;
    public static final dn X;
    public static final dn Y;
    public static final dn Z;
    public static final dn aa;
    public static final dn ab;
    public static final dn ac;
    public static final dn ad;
    public static final dn ae;
    public static final dn af;
    public static final dn ag;
    public static final dn ah;
    public static final dn ai;
    public static final dn aj;
    public static final dn ak;
    public static final dn al;
    public static final cg am;
    public static final cg an;
    public static final cg ao;
    public static final cg ap;
    public static final cg aq;
    public static final cg ar;
    public static final cg as;
    public static final cg at;
    public static final cg au;
    public static final cg av;
    public static final cg aw;
    public static final cg ax;
    public static final cg ay;
    public static final cg az;
    public static final cg aA;
    public static final cg aB;
    public static final cg aC;
    public static final cg aD;
    public static final cg aE;
    public static final cg aF;
    public static final cg aG;
    public static final cg aH;
    public static final cg aI;
    public static final cg aJ;
    public static final cg aK;
    public static final cg aL;
    public static final cg aM;
    public static final cg aN;
    public static final cg aO;
    public static final cg aP;
    public static final cg aQ;
    public static final cg aR;
    public static final cg aS;
    public static final cg aT;
    public static final cg aU;
    public static final cg aV;
    public static final cg aW;
    public static final cg aX;
    public static final cl aY;
    public static final cg aZ;
    public static final cg ba;
    public static final cg bb;
    public static final cg bc;
    public static final cg bd;
    public static final cg be;
    public static final cg bf;
    public static final cg bg;
    public static final cg bh;
    public static final cg bi;
    public static final cg bj;
    public static final bf bk;
    public static final ak bl;
    public static final cg bm;
    public static final cg bn;
    public static final cg bo;
    public static final cg bp;
    public static final cg bq;
    public static final cg br;
    public static final cg bs;
    public static final cg bt;
    public static final cg bu;
    public static final cg bv;
    public static final cg bw;
    public static final cg bx;
    public static final cg by;
    public static final cg bz;
    public static final cg bA;
    public static final cg bB;
    public static final cg bC;
    public static final cg bD;
    public static final cg bE;
    public static final cg bF;
    public static final ae bG;
    public static final ae bH;
    public static final ae bI;
    public static final cg bJ;
    public static final cg bK;
    public static final cg bL;
    public static final cg bM;
    public static final cg bN;
    public static final cg bO;
    public static final cg bP;
    public static final cg bQ;
    public static final cg bR;
    public static final cg bS;
    public static final cg bT;
    public static final cg bU;
    public static final cg bV;
    public static final cg bW;
    public static final cg bX;
    public static final cg bY;
    public static final cg bZ;
    public static final cg ca;
    public static final cg cb;
    public static final cg cc;
    public static final cg cd;
    public static final cg ce;
    public static final f cf;
    public static final cg cg;
    public static final cg ch;
    public static final cg ci;
    public static final cg cj;
    public static final cg ck;
    public static final cg cl;
    public static final cg cm;
    public static final al cn;
    public static final cg co;
    public static final cg cp;
    public static final cg cq;
    public static final cg cr;
    public static final cg cs;
    public static final aq ct;
    public static final cg cu;
    public static final cg cv;
    public static final cg cw;
    public static final cg cx;
    public static final cg cy;
    public static final cg cz;
    public static final cg cA;
    public static final cg cB;
    public static final cg cC;
    public static final cg cD;
    public static final cg cE;
    public static final cg cF;
    public static final cg cG;
    public static final cg cH;
    public static final cg cI;
    public static final cg cJ;
    public static final cg cK;
    public static final cg cL;
    public static final cg cM;
    public static final cg cN;
    public static final cg cO;
    public static final cg cP;
    public static final cg cQ;
    public static final cg cR;
    public static final cg cS;
    public static final cg cT;
    public static final cg cU;
    public static final cg cV;
    public static final cg cW;

    static {
        if (!net.minecraft.a.z.a()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        a = net.minecraft.a.w.a("iron_shovel");
        b = net.minecraft.a.w.a("iron_pickaxe");
        c = net.minecraft.a.w.a("iron_axe");
        d = net.minecraft.a.w.a("flint_and_steel");
        e = net.minecraft.a.w.a("apple");
        f = (bn)net.minecraft.a.w.a("bow");
        g = net.minecraft.a.w.a("arrow");
        h = net.minecraft.a.w.a("spectral_arrow");
        i = net.minecraft.a.w.a("tipped_arrow");
        j = net.minecraft.a.w.a("coal");
        k = net.minecraft.a.w.a("diamond");
        l = net.minecraft.a.w.a("iron_ingot");
        m = net.minecraft.a.w.a("gold_ingot");
        n = net.minecraft.a.w.a("iron_sword");
        o = net.minecraft.a.w.a("wooden_sword");
        p = net.minecraft.a.w.a("wooden_shovel");
        q = net.minecraft.a.w.a("wooden_pickaxe");
        r = net.minecraft.a.w.a("wooden_axe");
        s = net.minecraft.a.w.a("stone_sword");
        t = net.minecraft.a.w.a("stone_shovel");
        u = net.minecraft.a.w.a("stone_pickaxe");
        v = net.minecraft.a.w.a("stone_axe");
        w = net.minecraft.a.w.a("diamond_sword");
        x = net.minecraft.a.w.a("diamond_shovel");
        y = net.minecraft.a.w.a("diamond_pickaxe");
        z = net.minecraft.a.w.a("diamond_axe");
        A = net.minecraft.a.w.a("stick");
        B = net.minecraft.a.w.a("bowl");
        C = net.minecraft.a.w.a("mushroom_stew");
        D = net.minecraft.a.w.a("golden_sword");
        E = net.minecraft.a.w.a("golden_shovel");
        F = net.minecraft.a.w.a("golden_pickaxe");
        G = net.minecraft.a.w.a("golden_axe");
        H = net.minecraft.a.w.a("string");
        I = net.minecraft.a.w.a("feather");
        J = net.minecraft.a.w.a("gunpowder");
        K = net.minecraft.a.w.a("wooden_hoe");
        L = net.minecraft.a.w.a("stone_hoe");
        M = net.minecraft.a.w.a("iron_hoe");
        N = net.minecraft.a.w.a("diamond_hoe");
        O = net.minecraft.a.w.a("golden_hoe");
        P = net.minecraft.a.w.a("wheat_seeds");
        Q = net.minecraft.a.w.a("wheat");
        R = net.minecraft.a.w.a("bread");
        S = (dn)net.minecraft.a.w.a("leather_helmet");
        T = (dn)net.minecraft.a.w.a("leather_chestplate");
        U = (dn)net.minecraft.a.w.a("leather_leggings");
        V = (dn)net.minecraft.a.w.a("leather_boots");
        W = (dn)net.minecraft.a.w.a("chainmail_helmet");
        X = (dn)net.minecraft.a.w.a("chainmail_chestplate");
        Y = (dn)net.minecraft.a.w.a("chainmail_leggings");
        Z = (dn)net.minecraft.a.w.a("chainmail_boots");
        aa = (dn)net.minecraft.a.w.a("iron_helmet");
        ab = (dn)net.minecraft.a.w.a("iron_chestplate");
        ac = (dn)net.minecraft.a.w.a("iron_leggings");
        ad = (dn)net.minecraft.a.w.a("iron_boots");
        ae = (dn)net.minecraft.a.w.a("diamond_helmet");
        af = (dn)net.minecraft.a.w.a("diamond_chestplate");
        ag = (dn)net.minecraft.a.w.a("diamond_leggings");
        ah = (dn)net.minecraft.a.w.a("diamond_boots");
        ai = (dn)net.minecraft.a.w.a("golden_helmet");
        aj = (dn)net.minecraft.a.w.a("golden_chestplate");
        ak = (dn)net.minecraft.a.w.a("golden_leggings");
        al = (dn)net.minecraft.a.w.a("golden_boots");
        am = net.minecraft.a.w.a("flint");
        an = net.minecraft.a.w.a("porkchop");
        ao = net.minecraft.a.w.a("cooked_porkchop");
        ap = net.minecraft.a.w.a("painting");
        aq = net.minecraft.a.w.a("golden_apple");
        ar = net.minecraft.a.w.a("sign");
        as = net.minecraft.a.w.a("wooden_door");
        at = net.minecraft.a.w.a("spruce_door");
        au = net.minecraft.a.w.a("birch_door");
        av = net.minecraft.a.w.a("jungle_door");
        aw = net.minecraft.a.w.a("acacia_door");
        ax = net.minecraft.a.w.a("dark_oak_door");
        ay = net.minecraft.a.w.a("bucket");
        az = net.minecraft.a.w.a("water_bucket");
        aA = net.minecraft.a.w.a("lava_bucket");
        aB = net.minecraft.a.w.a("minecart");
        aC = net.minecraft.a.w.a("saddle");
        aD = net.minecraft.a.w.a("iron_door");
        aE = net.minecraft.a.w.a("redstone");
        aF = net.minecraft.a.w.a("snowball");
        aG = net.minecraft.a.w.a("boat");
        aH = net.minecraft.a.w.a("spruce_boat");
        aI = net.minecraft.a.w.a("birch_boat");
        aJ = net.minecraft.a.w.a("jungle_boat");
        aK = net.minecraft.a.w.a("acacia_boat");
        aL = net.minecraft.a.w.a("dark_oak_boat");
        aM = net.minecraft.a.w.a("leather");
        aN = net.minecraft.a.w.a("milk_bucket");
        aO = net.minecraft.a.w.a("brick");
        aP = net.minecraft.a.w.a("clay_ball");
        aQ = net.minecraft.a.w.a("reeds");
        aR = net.minecraft.a.w.a("paper");
        aS = net.minecraft.a.w.a("book");
        aT = net.minecraft.a.w.a("slime_ball");
        aU = net.minecraft.a.w.a("chest_minecart");
        aV = net.minecraft.a.w.a("furnace_minecart");
        aW = net.minecraft.a.w.a("egg");
        aX = net.minecraft.a.w.a("compass");
        aY = (cl)net.minecraft.a.w.a("fishing_rod");
        aZ = net.minecraft.a.w.a("clock");
        ba = net.minecraft.a.w.a("glowstone_dust");
        bb = net.minecraft.a.w.a("fish");
        bc = net.minecraft.a.w.a("cooked_fish");
        bd = net.minecraft.a.w.a("dye");
        be = net.minecraft.a.w.a("bone");
        bf = net.minecraft.a.w.a("sugar");
        bg = net.minecraft.a.w.a("cake");
        bh = net.minecraft.a.w.a("bed");
        bi = net.minecraft.a.w.a("repeater");
        bj = net.minecraft.a.w.a("cookie");
        bk = (bf)net.minecraft.a.w.a("filled_map");
        bl = (ak)net.minecraft.a.w.a("shears");
        bm = net.minecraft.a.w.a("melon");
        bn = net.minecraft.a.w.a("pumpkin_seeds");
        bo = net.minecraft.a.w.a("melon_seeds");
        bp = net.minecraft.a.w.a("beef");
        bq = net.minecraft.a.w.a("cooked_beef");
        br = net.minecraft.a.w.a("chicken");
        bs = net.minecraft.a.w.a("cooked_chicken");
        bt = net.minecraft.a.w.a("mutton");
        bu = net.minecraft.a.w.a("cooked_mutton");
        bv = net.minecraft.a.w.a("rabbit");
        bw = net.minecraft.a.w.a("cooked_rabbit");
        bx = net.minecraft.a.w.a("rabbit_stew");
        by = net.minecraft.a.w.a("rabbit_foot");
        bz = net.minecraft.a.w.a("rabbit_hide");
        bA = net.minecraft.a.w.a("rotten_flesh");
        bB = net.minecraft.a.w.a("ender_pearl");
        bC = net.minecraft.a.w.a("blaze_rod");
        bD = net.minecraft.a.w.a("ghast_tear");
        bE = net.minecraft.a.w.a("gold_nugget");
        bF = net.minecraft.a.w.a("nether_wart");
        bG = (ae)net.minecraft.a.w.a("potion");
        bH = (ae)net.minecraft.a.w.a("splash_potion");
        bI = (ae)net.minecraft.a.w.a("lingering_potion");
        bJ = net.minecraft.a.w.a("glass_bottle");
        bK = net.minecraft.a.w.a("dragon_breath");
        bL = net.minecraft.a.w.a("spider_eye");
        bM = net.minecraft.a.w.a("fermented_spider_eye");
        bN = net.minecraft.a.w.a("blaze_powder");
        bO = net.minecraft.a.w.a("magma_cream");
        bP = net.minecraft.a.w.a("brewing_stand");
        bQ = net.minecraft.a.w.a("cauldron");
        bR = net.minecraft.a.w.a("ender_eye");
        bS = net.minecraft.a.w.a("speckled_melon");
        bT = net.minecraft.a.w.a("spawn_egg");
        bU = net.minecraft.a.w.a("experience_bottle");
        bV = net.minecraft.a.w.a("fire_charge");
        bW = net.minecraft.a.w.a("writable_book");
        bX = net.minecraft.a.w.a("written_book");
        bY = net.minecraft.a.w.a("emerald");
        bZ = net.minecraft.a.w.a("item_frame");
        ca = net.minecraft.a.w.a("flower_pot");
        cb = net.minecraft.a.w.a("carrot");
        cc = net.minecraft.a.w.a("potato");
        cd = net.minecraft.a.w.a("baked_potato");
        ce = net.minecraft.a.w.a("poisonous_potato");
        cf = (f)net.minecraft.a.w.a("map");
        cg = net.minecraft.a.w.a("golden_carrot");
        ch = net.minecraft.a.w.a("skull");
        ci = net.minecraft.a.w.a("carrot_on_a_stick");
        cj = net.minecraft.a.w.a("nether_star");
        ck = net.minecraft.a.w.a("pumpkin_pie");
        cl = net.minecraft.a.w.a("fireworks");
        cm = net.minecraft.a.w.a("firework_charge");
        cn = (al)net.minecraft.a.w.a("enchanted_book");
        co = net.minecraft.a.w.a("comparator");
        cp = net.minecraft.a.w.a("netherbrick");
        cq = net.minecraft.a.w.a("quartz");
        cr = net.minecraft.a.w.a("tnt_minecart");
        cs = net.minecraft.a.w.a("hopper_minecart");
        ct = (aq)net.minecraft.a.w.a("armor_stand");
        cu = net.minecraft.a.w.a("iron_horse_armor");
        cv = net.minecraft.a.w.a("golden_horse_armor");
        cw = net.minecraft.a.w.a("diamond_horse_armor");
        cx = net.minecraft.a.w.a("lead");
        cy = net.minecraft.a.w.a("name_tag");
        cz = net.minecraft.a.w.a("command_block_minecart");
        cA = net.minecraft.a.w.a("record_13");
        cB = net.minecraft.a.w.a("record_cat");
        cC = net.minecraft.a.w.a("record_blocks");
        cD = net.minecraft.a.w.a("record_chirp");
        cE = net.minecraft.a.w.a("record_far");
        cF = net.minecraft.a.w.a("record_mall");
        cG = net.minecraft.a.w.a("record_mellohi");
        cH = net.minecraft.a.w.a("record_stal");
        cI = net.minecraft.a.w.a("record_strad");
        cJ = net.minecraft.a.w.a("record_ward");
        cK = net.minecraft.a.w.a("record_11");
        cL = net.minecraft.a.w.a("record_wait");
        cM = net.minecraft.a.w.a("prismarine_shard");
        cN = net.minecraft.a.w.a("prismarine_crystals");
        cO = net.minecraft.a.w.a("banner");
        cP = net.minecraft.a.w.a("end_crystal");
        cQ = net.minecraft.a.w.a("shield");
        cR = net.minecraft.a.w.a("elytra");
        cS = net.minecraft.a.w.a("chorus_fruit");
        cT = net.minecraft.a.w.a("chorus_fruit_popped");
        cU = net.minecraft.a.w.a("beetroot_seeds");
        cV = net.minecraft.a.w.a("beetroot");
        cW = net.minecraft.a.w.a("beetroot_soup");
    }

    private static cg a(String string) {
        cg cg2 = (cg)net.minecraft.m.cg.e.a(new bp(string));
        if (cg2 == null) {
            throw new IllegalStateException("Invalid Item requested: " + string);
        }
        return cg2;
    }
}

