/*
 * Decompiled with CFR 0.150.
 */
package com.ibm.icu.b;

import com.ibm.icu.a.hk;
import com.ibm.icu.b.b;
import java.lang.ref.SoftReference;
import java.util.HashMap;
import java.util.Locale;

/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public final class q
extends Character.Subset {
    public static final int a = -1;
    public static final int b = 1;
    public static final int c = 2;
    public static final int d = 3;
    public static final int e = 4;
    public static final int f = 5;
    public static final int g = 6;
    public static final int h = 7;
    public static final int i = 8;
    public static final int j = 9;
    public static final int k = 10;
    public static final int l = 11;
    public static final int m = 12;
    public static final int n = 13;
    public static final int o = 14;
    public static final int p = 15;
    public static final int q = 16;
    public static final int r = 17;
    public static final int s = 18;
    public static final int t = 19;
    public static final int u = 20;
    public static final int v = 21;
    public static final int w = 22;
    public static final int x = 23;
    public static final int y = 24;
    public static final int z = 25;
    public static final int A = 26;
    public static final int B = 27;
    public static final int C = 28;
    public static final int D = 29;
    public static final int E = 30;
    public static final int F = 31;
    public static final int G = 32;
    public static final int H = 33;
    public static final int I = 34;
    public static final int J = 35;
    public static final int K = 36;
    public static final int L = 37;
    public static final int M = 38;
    public static final int N = 39;
    public static final int O = 40;
    public static final int P = 41;
    public static final int Q = 42;
    public static final int R = 43;
    public static final int S = 44;
    public static final int T = 45;
    public static final int U = 46;
    public static final int V = 47;
    public static final int W = 48;
    public static final int X = 49;
    public static final int Y = 50;
    public static final int Z = 51;
    public static final int aa = 52;
    public static final int ab = 53;
    public static final int ac = 54;
    public static final int ad = 55;
    public static final int ae = 56;
    public static final int af = 57;
    public static final int ag = 58;
    public static final int ah = 59;
    public static final int ai = 60;
    public static final int aj = 61;
    public static final int ak = 62;
    public static final int al = 63;
    public static final int am = 64;
    public static final int an = 65;
    public static final int ao = 66;
    public static final int ap = 67;
    public static final int aq = 68;
    public static final int ar = 69;
    public static final int as = 70;
    public static final int at = 71;
    public static final int au = 72;
    public static final int av = 73;
    public static final int aw = 74;
    public static final int ax = 75;
    public static final int ay = 76;
    public static final int az = 77;
    public static final int aA = 78;
    public static final int aB = 78;
    public static final int aC = 79;
    public static final int aD = 80;
    public static final int aE = 81;
    public static final int aF = 82;
    public static final int aG = 83;
    public static final int aH = 84;
    public static final int aI = 85;
    public static final int aJ = 86;
    public static final int aK = 87;
    public static final int aL = 88;
    public static final int aM = 89;
    public static final int aN = 90;
    public static final int aO = 91;
    public static final int aP = 92;
    public static final int aQ = 93;
    public static final int aR = 94;
    public static final int aS = 95;
    public static final int aT = 96;
    public static final int aU = 97;
    public static final int aV = 97;
    public static final int aW = 98;
    public static final int aX = 99;
    public static final int aY = 100;
    public static final int aZ = 101;
    public static final int ba = 102;
    public static final int bb = 103;
    public static final int bc = 104;
    public static final int bd = 105;
    public static final int be = 106;
    public static final int bf = 107;
    public static final int bg = 108;
    public static final int bh = 109;
    public static final int bi = 110;
    public static final int bj = 111;
    public static final int bk = 112;
    public static final int bl = 113;
    public static final int bm = 114;
    public static final int bn = 115;
    public static final int bo = 116;
    public static final int bp = 117;
    public static final int bq = 118;
    public static final int br = 119;
    public static final int bs = 120;
    public static final int bt = 121;
    public static final int bu = 122;
    public static final int bv = 123;
    public static final int bw = 124;
    public static final int bx = 125;
    public static final int by = 126;
    public static final int bz = 127;
    public static final int bA = 128;
    public static final int bB = 129;
    public static final int bC = 130;
    public static final int bD = 131;
    public static final int bE = 132;
    public static final int bF = 133;
    public static final int bG = 134;
    public static final int bH = 135;
    public static final int bI = 136;
    public static final int bJ = 137;
    public static final int bK = 138;
    public static final int bL = 139;
    public static final int bM = 140;
    public static final int bN = 141;
    public static final int bO = 142;
    public static final int bP = 143;
    public static final int bQ = 144;
    public static final int bR = 145;
    public static final int bS = 146;
    public static final int bT = 147;
    public static final int bU = 148;
    public static final int bV = 149;
    public static final int bW = 150;
    public static final int bX = 151;
    public static final int bY = 152;
    public static final int bZ = 153;
    public static final int ca = 154;
    public static final int cb = 155;
    public static final int cc = 156;
    public static final int cd = 157;
    public static final int ce = 158;
    public static final int cf = 159;
    public static final int cg = 160;
    public static final int ch = 161;
    public static final int ci = 162;
    public static final int cj = 163;
    public static final int ck = 164;
    public static final int cl = 165;
    public static final int cm = 166;
    public static final int cn = 167;
    public static final int co = 168;
    public static final int cp = 169;
    public static final int cq = 170;
    public static final int cr = 171;
    public static final int cs = 172;
    public static final int ct = 173;
    public static final int cu = 174;
    public static final int cv = 175;
    public static final int cw = 176;
    public static final int cx = 177;
    public static final int cy = 178;
    public static final int cz = 179;
    public static final int cA = 180;
    public static final int cB = 181;
    public static final int cC = 182;
    public static final int cD = 183;
    public static final int cE = 184;
    public static final int cF = 185;
    public static final int cG = 186;
    public static final int cH = 187;
    public static final int cI = 188;
    public static final int cJ = 189;
    public static final int cK = 190;
    public static final int cL = 191;
    public static final int cM = 192;
    public static final int cN = 193;
    public static final int cO = 194;
    public static final int cP = 195;
    public static final int cQ = 196;
    public static final int cR = 197;
    public static final int cS = 198;
    public static final int cT = 199;
    public static final int cU = 200;
    public static final int cV = 201;
    public static final int cW = 202;
    public static final int cX = 203;
    public static final int cY = 204;
    public static final int cZ = 205;
    public static final int da = 206;
    public static final int db = 207;
    public static final int dc = 208;
    public static final int dd = 209;
    public static final int de = 210;
    public static final int df = 211;
    public static final int dg = 212;
    public static final int dh = 213;
    public static final int di = 214;
    public static final int dj = 215;
    public static final int dk = 216;
    public static final int dl = 217;
    public static final int dm = 218;
    public static final int dn = 219;
    public static final int do = 220;
    public static final int dp = 221;
    private static final q[] hG = new q[221];
    public static final q dq = new q("NO_BLOCK", 0);
    public static final q dr = new q("BASIC_LATIN", 1);
    public static final q ds = new q("LATIN_1_SUPPLEMENT", 2);
    public static final q dt = new q("LATIN_EXTENDED_A", 3);
    public static final q du = new q("LATIN_EXTENDED_B", 4);
    public static final q dv = new q("IPA_EXTENSIONS", 5);
    public static final q dw = new q("SPACING_MODIFIER_LETTERS", 6);
    public static final q dx = new q("COMBINING_DIACRITICAL_MARKS", 7);
    public static final q dy = new q("GREEK", 8);
    public static final q dz = new q("CYRILLIC", 9);
    public static final q dA = new q("ARMENIAN", 10);
    public static final q dB = new q("HEBREW", 11);
    public static final q dC = new q("ARABIC", 12);
    public static final q dD = new q("SYRIAC", 13);
    public static final q dE = new q("THAANA", 14);
    public static final q dF = new q("DEVANAGARI", 15);
    public static final q dG = new q("BENGALI", 16);
    public static final q dH = new q("GURMUKHI", 17);
    public static final q dI = new q("GUJARATI", 18);
    public static final q dJ = new q("ORIYA", 19);
    public static final q dK = new q("TAMIL", 20);
    public static final q dL = new q("TELUGU", 21);
    public static final q dM = new q("KANNADA", 22);
    public static final q dN = new q("MALAYALAM", 23);
    public static final q dO = new q("SINHALA", 24);
    public static final q dP = new q("THAI", 25);
    public static final q dQ = new q("LAO", 26);
    public static final q dR = new q("TIBETAN", 27);
    public static final q dS = new q("MYANMAR", 28);
    public static final q dT = new q("GEORGIAN", 29);
    public static final q dU = new q("HANGUL_JAMO", 30);
    public static final q dV = new q("ETHIOPIC", 31);
    public static final q dW = new q("CHEROKEE", 32);
    public static final q dX = new q("UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS", 33);
    public static final q dY = new q("OGHAM", 34);
    public static final q dZ = new q("RUNIC", 35);
    public static final q ea = new q("KHMER", 36);
    public static final q eb = new q("MONGOLIAN", 37);
    public static final q ec = new q("LATIN_EXTENDED_ADDITIONAL", 38);
    public static final q ed = new q("GREEK_EXTENDED", 39);
    public static final q ee = new q("GENERAL_PUNCTUATION", 40);
    public static final q ef = new q("SUPERSCRIPTS_AND_SUBSCRIPTS", 41);
    public static final q eg = new q("CURRENCY_SYMBOLS", 42);
    public static final q eh = new q("COMBINING_MARKS_FOR_SYMBOLS", 43);
    public static final q ei = new q("LETTERLIKE_SYMBOLS", 44);
    public static final q ej = new q("NUMBER_FORMS", 45);
    public static final q ek = new q("ARROWS", 46);
    public static final q el = new q("MATHEMATICAL_OPERATORS", 47);
    public static final q em = new q("MISCELLANEOUS_TECHNICAL", 48);
    public static final q en = new q("CONTROL_PICTURES", 49);
    public static final q eo = new q("OPTICAL_CHARACTER_RECOGNITION", 50);
    public static final q ep = new q("ENCLOSED_ALPHANUMERICS", 51);
    public static final q eq = new q("BOX_DRAWING", 52);
    public static final q er = new q("BLOCK_ELEMENTS", 53);
    public static final q es = new q("GEOMETRIC_SHAPES", 54);
    public static final q et = new q("MISCELLANEOUS_SYMBOLS", 55);
    public static final q eu = new q("DINGBATS", 56);
    public static final q ev = new q("BRAILLE_PATTERNS", 57);
    public static final q ew = new q("CJK_RADICALS_SUPPLEMENT", 58);
    public static final q ex = new q("KANGXI_RADICALS", 59);
    public static final q ey = new q("IDEOGRAPHIC_DESCRIPTION_CHARACTERS", 60);
    public static final q ez = new q("CJK_SYMBOLS_AND_PUNCTUATION", 61);
    public static final q eA = new q("HIRAGANA", 62);
    public static final q eB = new q("KATAKANA", 63);
    public static final q eC = new q("BOPOMOFO", 64);
    public static final q eD = new q("HANGUL_COMPATIBILITY_JAMO", 65);
    public static final q eE = new q("KANBUN", 66);
    public static final q eF = new q("BOPOMOFO_EXTENDED", 67);
    public static final q eG = new q("ENCLOSED_CJK_LETTERS_AND_MONTHS", 68);
    public static final q eH = new q("CJK_COMPATIBILITY", 69);
    public static final q eI = new q("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A", 70);
    public static final q eJ = new q("CJK_UNIFIED_IDEOGRAPHS", 71);
    public static final q eK = new q("YI_SYLLABLES", 72);
    public static final q eL = new q("YI_RADICALS", 73);
    public static final q eM = new q("HANGUL_SYLLABLES", 74);
    public static final q eN = new q("HIGH_SURROGATES", 75);
    public static final q eO = new q("HIGH_PRIVATE_USE_SURROGATES", 76);
    public static final q eP = new q("LOW_SURROGATES", 77);
    public static final q eQ;
    public static final q eR;
    public static final q eS;
    public static final q eT;
    public static final q eU;
    public static final q eV;
    public static final q eW;
    public static final q eX;
    public static final q eY;
    public static final q eZ;
    public static final q fa;
    public static final q fb;
    public static final q fc;
    public static final q fd;
    public static final q fe;
    public static final q ff;
    public static final q fg;
    public static final q fh;
    public static final q fi;
    public static final q fj;
    public static final q fk;
    public static final q fl;
    public static final q fm;
    public static final q fn;
    public static final q fo;
    public static final q fp;
    public static final q fq;
    public static final q fr;
    public static final q fs;
    public static final q ft;
    public static final q fu;
    public static final q fv;
    public static final q fw;
    public static final q fx;
    public static final q fy;
    public static final q fz;
    public static final q fA;
    public static final q fB;
    public static final q fC;
    public static final q fD;
    public static final q fE;
    public static final q fF;
    public static final q fG;
    public static final q fH;
    public static final q fI;
    public static final q fJ;
    public static final q fK;
    public static final q fL;
    public static final q fM;
    public static final q fN;
    public static final q fO;
    public static final q fP;
    public static final q fQ;
    public static final q fR;
    public static final q fS;
    public static final q fT;
    public static final q fU;
    public static final q fV;
    public static final q fW;
    public static final q fX;
    public static final q fY;
    public static final q fZ;
    public static final q ga;
    public static final q gb;
    public static final q gc;
    public static final q gd;
    public static final q ge;
    public static final q gf;
    public static final q gg;
    public static final q gh;
    public static final q gi;
    public static final q gj;
    public static final q gk;
    public static final q gl;
    public static final q gm;
    public static final q gn;
    public static final q go;
    public static final q gp;
    public static final q gq;
    public static final q gr;
    public static final q gs;
    public static final q gt;
    public static final q gu;
    public static final q gv;
    public static final q gw;
    public static final q gx;
    public static final q gy;
    public static final q gz;
    public static final q gA;
    public static final q gB;
    public static final q gC;
    public static final q gD;
    public static final q gE;
    public static final q gF;
    public static final q gG;
    public static final q gH;
    public static final q gI;
    public static final q gJ;
    public static final q gK;
    public static final q gL;
    public static final q gM;
    public static final q gN;
    public static final q gO;
    public static final q gP;
    public static final q gQ;
    public static final q gR;
    public static final q gS;
    public static final q gT;
    public static final q gU;
    public static final q gV;
    public static final q gW;
    public static final q gX;
    public static final q gY;
    public static final q gZ;
    public static final q ha;
    public static final q hb;
    public static final q hc;
    public static final q hd;
    public static final q he;
    public static final q hf;
    public static final q hg;
    public static final q hh;
    public static final q hi;
    public static final q hj;
    public static final q hk;
    public static final q hl;
    public static final q hm;
    public static final q hn;
    public static final q ho;
    public static final q hp;
    public static final q hq;
    public static final q hr;
    public static final q hs;
    public static final q ht;
    public static final q hu;
    public static final q hv;
    public static final q hw;
    public static final q hx;
    public static final q hy;
    public static final q hz;
    public static final q hA;
    public static final q hB;
    public static final q hC;
    public static final q hD;
    public static final q hE;
    public static final q hF;
    private static SoftReference hH;
    private int hI;

    public static q a(int n2) {
        if (n2 >= 0 && n2 < hG.length) {
            return hG[n2];
        }
        return hF;
    }

    public static q b(int n2) {
        if (n2 > 0x10FFFF) {
            return hF;
        }
        return com.ibm.icu.b.q.a(com.ibm.icu.a.hk.a.c(n2, 4097));
    }

    public static final q a(String string) {
        q q2;
        HashMap<String, q> hashMap = null;
        if (hH != null) {
            hashMap = (HashMap<String, q>)hH.get();
        }
        if (hashMap == null) {
            hashMap = new HashMap<String, q>(hG.length);
            for (int i2 = 0; i2 < hG.length; ++i2) {
                q q3 = hG[i2];
                String string2 = com.ibm.icu.b.q.b(com.ibm.icu.b.b.a(4097, q3.a(), 1));
                hashMap.put(string2, q3);
            }
            hH = new SoftReference(hashMap);
        }
        if ((q2 = (q)hashMap.get(com.ibm.icu.b.q.b(string))) == null) {
            throw new IllegalArgumentException();
        }
        return q2;
    }

    private static String b(String string) {
        String string2 = string.toUpperCase(Locale.ENGLISH);
        StringBuilder stringBuilder = new StringBuilder(string2.length());
        for (int i2 = 0; i2 < string2.length(); ++i2) {
            char c2 = string2.charAt(i2);
            if (c2 == ' ' || c2 == '_' || c2 == '-') continue;
            stringBuilder.append(c2);
        }
        return stringBuilder.toString();
    }

    public int a() {
        return this.hI;
    }

    private q(String string, int n2) {
        super(string);
        this.hI = n2;
        if (n2 >= 0) {
            com.ibm.icu.b.q.hG[n2] = this;
        }
    }

    static {
        eR = eQ = new q("PRIVATE_USE_AREA", 78);
        eS = new q("CJK_COMPATIBILITY_IDEOGRAPHS", 79);
        eT = new q("ALPHABETIC_PRESENTATION_FORMS", 80);
        eU = new q("ARABIC_PRESENTATION_FORMS_A", 81);
        eV = new q("COMBINING_HALF_MARKS", 82);
        eW = new q("CJK_COMPATIBILITY_FORMS", 83);
        eX = new q("SMALL_FORM_VARIANTS", 84);
        eY = new q("ARABIC_PRESENTATION_FORMS_B", 85);
        eZ = new q("SPECIALS", 86);
        fa = new q("HALFWIDTH_AND_FULLWIDTH_FORMS", 87);
        fb = new q("OLD_ITALIC", 88);
        fc = new q("GOTHIC", 89);
        fd = new q("DESERET", 90);
        fe = new q("BYZANTINE_MUSICAL_SYMBOLS", 91);
        ff = new q("MUSICAL_SYMBOLS", 92);
        fg = new q("MATHEMATICAL_ALPHANUMERIC_SYMBOLS", 93);
        fh = new q("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B", 94);
        fi = new q("CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT", 95);
        fj = new q("TAGS", 96);
        fk = new q("CYRILLIC_SUPPLEMENTARY", 97);
        fl = new q("CYRILLIC_SUPPLEMENT", 97);
        fm = new q("TAGALOG", 98);
        fn = new q("HANUNOO", 99);
        fo = new q("BUHID", 100);
        fp = new q("TAGBANWA", 101);
        fq = new q("MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A", 102);
        fr = new q("SUPPLEMENTAL_ARROWS_A", 103);
        fs = new q("SUPPLEMENTAL_ARROWS_B", 104);
        ft = new q("MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B", 105);
        fu = new q("SUPPLEMENTAL_MATHEMATICAL_OPERATORS", 106);
        fv = new q("KATAKANA_PHONETIC_EXTENSIONS", 107);
        fw = new q("VARIATION_SELECTORS", 108);
        fx = new q("SUPPLEMENTARY_PRIVATE_USE_AREA_A", 109);
        fy = new q("SUPPLEMENTARY_PRIVATE_USE_AREA_B", 110);
        fz = new q("LIMBU", 111);
        fA = new q("TAI_LE", 112);
        fB = new q("KHMER_SYMBOLS", 113);
        fC = new q("PHONETIC_EXTENSIONS", 114);
        fD = new q("MISCELLANEOUS_SYMBOLS_AND_ARROWS", 115);
        fE = new q("YIJING_HEXAGRAM_SYMBOLS", 116);
        fF = new q("LINEAR_B_SYLLABARY", 117);
        fG = new q("LINEAR_B_IDEOGRAMS", 118);
        fH = new q("AEGEAN_NUMBERS", 119);
        fI = new q("UGARITIC", 120);
        fJ = new q("SHAVIAN", 121);
        fK = new q("OSMANYA", 122);
        fL = new q("CYPRIOT_SYLLABARY", 123);
        fM = new q("TAI_XUAN_JING_SYMBOLS", 124);
        fN = new q("VARIATION_SELECTORS_SUPPLEMENT", 125);
        fO = new q("ANCIENT_GREEK_MUSICAL_NOTATION", 126);
        fP = new q("ANCIENT_GREEK_NUMBERS", 127);
        fQ = new q("ARABIC_SUPPLEMENT", 128);
        fR = new q("BUGINESE", 129);
        fS = new q("CJK_STROKES", 130);
        fT = new q("COMBINING_DIACRITICAL_MARKS_SUPPLEMENT", 131);
        fU = new q("COPTIC", 132);
        fV = new q("ETHIOPIC_EXTENDED", 133);
        fW = new q("ETHIOPIC_SUPPLEMENT", 134);
        fX = new q("GEORGIAN_SUPPLEMENT", 135);
        fY = new q("GLAGOLITIC", 136);
        fZ = new q("KHAROSHTHI", 137);
        ga = new q("MODIFIER_TONE_LETTERS", 138);
        gb = new q("NEW_TAI_LUE", 139);
        gc = new q("OLD_PERSIAN", 140);
        gd = new q("PHONETIC_EXTENSIONS_SUPPLEMENT", 141);
        ge = new q("SUPPLEMENTAL_PUNCTUATION", 142);
        gf = new q("SYLOTI_NAGRI", 143);
        gg = new q("TIFINAGH", 144);
        gh = new q("VERTICAL_FORMS", 145);
        gi = new q("NKO", 146);
        gj = new q("BALINESE", 147);
        gk = new q("LATIN_EXTENDED_C", 148);
        gl = new q("LATIN_EXTENDED_D", 149);
        gm = new q("PHAGS_PA", 150);
        gn = new q("PHOENICIAN", 151);
        go = new q("CUNEIFORM", 152);
        gp = new q("CUNEIFORM_NUMBERS_AND_PUNCTUATION", 153);
        gq = new q("COUNTING_ROD_NUMERALS", 154);
        gr = new q("SUNDANESE", 155);
        gs = new q("LEPCHA", 156);
        gt = new q("OL_CHIKI", 157);
        gu = new q("CYRILLIC_EXTENDED_A", 158);
        gv = new q("VAI", 159);
        gw = new q("CYRILLIC_EXTENDED_B", 160);
        gx = new q("SAURASHTRA", 161);
        gy = new q("KAYAH_LI", 162);
        gz = new q("REJANG", 163);
        gA = new q("CHAM", 164);
        gB = new q("ANCIENT_SYMBOLS", 165);
        gC = new q("PHAISTOS_DISC", 166);
        gD = new q("LYCIAN", 167);
        gE = new q("CARIAN", 168);
        gF = new q("LYDIAN", 169);
        gG = new q("MAHJONG_TILES", 170);
        gH = new q("DOMINO_TILES", 171);
        gI = new q("SAMARITAN", 172);
        gJ = new q("UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED", 173);
        gK = new q("TAI_THAM", 174);
        gL = new q("VEDIC_EXTENSIONS", 175);
        gM = new q("LISU", 176);
        gN = new q("BAMUM", 177);
        gO = new q("COMMON_INDIC_NUMBER_FORMS", 178);
        gP = new q("DEVANAGARI_EXTENDED", 179);
        gQ = new q("HANGUL_JAMO_EXTENDED_A", 180);
        gR = new q("JAVANESE", 181);
        gS = new q("MYANMAR_EXTENDED_A", 182);
        gT = new q("TAI_VIET", 183);
        gU = new q("MEETEI_MAYEK", 184);
        gV = new q("HANGUL_JAMO_EXTENDED_B", 185);
        gW = new q("IMPERIAL_ARAMAIC", 186);
        gX = new q("OLD_SOUTH_ARABIAN", 187);
        gY = new q("AVESTAN", 188);
        gZ = new q("INSCRIPTIONAL_PARTHIAN", 189);
        ha = new q("INSCRIPTIONAL_PAHLAVI", 190);
        hb = new q("OLD_TURKIC", 191);
        hc = new q("RUMI_NUMERAL_SYMBOLS", 192);
        hd = new q("KAITHI", 193);
        he = new q("EGYPTIAN_HIEROGLYPHS", 194);
        hf = new q("ENCLOSED_ALPHANUMERIC_SUPPLEMENT", 195);
        hg = new q("ENCLOSED_IDEOGRAPHIC_SUPPLEMENT", 196);
        hh = new q("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C", 197);
        hi = new q("MANDAIC", 198);
        hj = new q("BATAK", 199);
        hk = new q("ETHIOPIC_EXTENDED_A", 200);
        hl = new q("BRAHMI", 201);
        hm = new q("BAMUM_SUPPLEMENT", 202);
        hn = new q("KANA_SUPPLEMENT", 203);
        ho = new q("PLAYING_CARDS", 204);
        hp = new q("MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS", 205);
        hq = new q("EMOTICONS", 206);
        hr = new q("TRANSPORT_AND_MAP_SYMBOLS", 207);
        hs = new q("ALCHEMICAL_SYMBOLS", 208);
        ht = new q("CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D", 209);
        hu = new q("ARABIC_EXTENDED_A", 210);
        hv = new q("ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS", 211);
        hw = new q("CHAKMA", 212);
        hx = new q("MEETEI_MAYEK_EXTENSIONS", 213);
        hy = new q("MEROITIC_CURSIVE", 214);
        hz = new q("MEROITIC_HIEROGLYPHS", 215);
        hA = new q("MIAO", 216);
        hB = new q("SHARADA", 217);
        hC = new q("SORA_SOMPENG", 218);
        hD = new q("SUNDANESE_SUPPLEMENT", 219);
        hE = new q("TAKRI", 220);
        hF = new q("INVALID_CODE", -1);
        for (int i2 = 0; i2 < 221; ++i2) {
            if (hG[i2] != null) continue;
            throw new IllegalStateException("UnicodeBlock.BLOCKS_[" + i2 + "] not initialized");
        }
    }
}

